/**
 * Project      : SMRITI Retail OS
 * Author       : Jawahar Ramkripal Mallah
 * Designation  : Chief Systems Architect & Creator
 * Email        : support@smritibooks.com
 * Websites     : smritibooks.com | erpnbook.com | aitdl.com
 * Version      : 3.122.0
 * Created      : 2026-08-28
 * Modified     : 2026-08-28
 * Copyright    : © SMRITIBooks.com. All Rights Reserved.
 * License      : Proprietary Commercial Software
 * Classification: Internal
 */

import { describe, it, expect } from "vitest";
import AutoPOEngine from "../utils/autoPOEngine";
import type { StockItem } from "../utils/autoPOEngine";

describe("AutoPOEngine — Purchase Order Auto-Generation Engine", () => {

  const ITEMS: StockItem[] = [
    { sku: "MED-PARA-500", productName: "Paracetamol 500mg",  branchCode: "BR-MUM-01", supplierId: "SUP-001", supplierName: "PharmaCo",   currentStock: 0,  reorderPoint: 50,  reorderQty: 200, supplierMOQ: 100, unitCost: 12,  leadTimeDays: 3 },
    { sku: "MED-AMOX-250", productName: "Amoxicillin 250mg",  branchCode: "BR-MUM-01", supplierId: "SUP-001", supplierName: "PharmaCo",   currentStock: 20, reorderPoint: 50,  reorderQty: 100, supplierMOQ: 50,  unitCost: 28,  leadTimeDays: 3 },
    { sku: "FAB-DENIM-BLU", productName: "Denim Blue 1m",    branchCode: "BR-MUM-01", supplierId: "SUP-002", supplierName: "FabricWorld", currentStock: 80, reorderPoint: 100, reorderQty: 300, supplierMOQ: 200, unitCost: 180, leadTimeDays: 7 },
    { sku: "FAB-LINEN-WHT", productName: "Linen White 1m",   branchCode: "BR-MUM-01", supplierId: "SUP-002", supplierName: "FabricWorld", currentStock: 200, reorderPoint: 50, reorderQty: 150, supplierMOQ: 100, unitCost: 200, leadTimeDays: 7 },  // No breach
  ];

  // ─── Test 1: detectBreaches — severity + suggestedQty + MOQ ─────────────
  it("detectBreaches finds only breached items; severity CRITICAL for stockOut; suggestedQty = max(reorderQty, MOQ)", () => {
    const breaches = AutoPOEngine.detectBreaches(ITEMS);

    // LINEN (200 > reorderPoint 50) should NOT breach
    expect(breaches.length).toBe(3);   // PARA, AMOX, DENIM breach
    expect(breaches.some((b) => b.sku === "FAB-LINEN-WHT")).toBe(false);

    const para = breaches.find((b) => b.sku === "MED-PARA-500")!;
    expect(para.severity).toBe("CRITICAL");     // currentStock = 0
    expect(para.suggestedQty).toBe(200);        // max(reorderQty=200, MOQ=100) = 200
    expect(para.lineTotal).toBe(2400);          // 200 × 12

    const amox = breaches.find((b) => b.sku === "MED-AMOX-250")!;
    expect(amox.severity).toBe("LOW");          // 20 ≤ 50/2 = 25
    expect(amox.suggestedQty).toBe(100);        // max(100, 50) = 100

    const denim = breaches.find((b) => b.sku === "FAB-DENIM-BLU")!;
    expect(denim.severity).toBe("NORMAL");      // 80 > 100/2 = 50
    expect(denim.suggestedQty).toBe(300);       // max(300, 200) = 300

    // Sorted: CRITICAL first
    expect(breaches[0].severity).toBe("CRITICAL");
  });

  // ─── Test 2: generatePO — single supplier; MOQ respected ─────────────────
  it("generatePO creates one PO per supplier with correct totalValue and expectedDelivery", () => {
    const breaches = AutoPOEngine.detectBreaches(ITEMS);
    const po = AutoPOEngine.generatePO(breaches, "SUP-001", "BR-MUM-01");

    expect(po.supplierId).toBe("SUP-001");
    expect(po.status).toBe("DRAFT");
    expect(po.isAutoGenerated).toBe(true);
    expect(po.lines).toHaveLength(2);           // PARA + AMOX
    expect(po.totalQty).toBe(300);              // 200 + 100
    expect(po.totalValue).toBe(200 * 12 + 100 * 28);  // 2400 + 2800 = 5200
    expect(po.poNo).toMatch(/^APO-BR-MUM-01-/);
    expect(po.expectedDelivery).toBeDefined();  // generatedAt + max(leadTime=3) days
  });

  // ─── Test 3: consolidatePOs — groups by supplier × branch ────────────────
  it("consolidatePOs returns one PO per unique supplierId+branchCode", () => {
    const breaches = AutoPOEngine.detectBreaches(ITEMS);
    const pos = AutoPOEngine.consolidatePOs(breaches);

    // SUP-001 (PARA + AMOX) and SUP-002 (DENIM) → 2 POs
    expect(pos).toHaveLength(2);
    const sup1PO = pos.find((p) => p.supplierId === "SUP-001")!;
    const sup2PO = pos.find((p) => p.supplierId === "SUP-002")!;
    expect(sup1PO.lines).toHaveLength(2);
    expect(sup2PO.lines).toHaveLength(1);
    expect(sup2PO.totalValue).toBe(300 * 180);  // 54000
  });

  // ─── Test 4: submit / acknowledge / cancel guards + poSummary ────────────
  it("submit→SUBMITTED; acknowledge→ACKNOWLEDGED; cancel on ACKNOWLEDGED throws; poSummary correct", () => {
    const breaches = AutoPOEngine.detectBreaches(ITEMS);
    let po = AutoPOEngine.generatePO(breaches, "SUP-001", "BR-MUM-01");

    po = AutoPOEngine.submit(po, "PURCHASE-MGR");
    expect(po.status).toBe("SUBMITTED");
    expect(po.submittedAt).toBeDefined();

    po = AutoPOEngine.acknowledge(po);
    expect(po.status).toBe("ACKNOWLEDGED");
    expect(po.acknowledgedAt).toBeDefined();

    // Cannot cancel once ACKNOWLEDGED
    expect(() => AutoPOEngine.cancel(po, "Late cancel")).toThrow("Cannot cancel");

    // Cancel from DRAFT
    let po2 = AutoPOEngine.generatePO(breaches, "SUP-002", "BR-MUM-01");
    po2 = AutoPOEngine.cancel(po2, "Budget freeze");
    expect(po2.status).toBe("CANCELLED");
    expect(po2.cancelReason).toBe("Budget freeze");

    const summary = AutoPOEngine.poSummary([po, po2]);
    expect(summary.totalPOs).toBe(2);
    expect(summary.byStatus["ACKNOWLEDGED"]).toBe(1);
    expect(summary.byStatus["CANCELLED"]).toBe(1);
    expect(summary.totalValue).toBe(po.totalValue + po2.totalValue);
  });
});
