"""
Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Designation  : Chief Systems Architect & Creator
Email        : support@smritibooks.com
Websites     : smritisys.com | smritibooks.com | erpnbook.com | aitdl.com
Version      : 3.40.0
Created      : 2026-07-20
Modified     : 2026-07-20
Copyright    : © SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software
"""

from datetime import datetime, date
from sqlalchemy import (
    Column, String, Numeric, Boolean, Integer, 
    Text, ForeignKey, Date, DateTime, Index
)
from sqlalchemy.orm import relationship
from ..db.base import BaseEntity


class StockTransferOrder(BaseEntity):
    """
    Inter-Store and Inter-Branch Stock Transfer Order (STO) supporting multi-tier approvals,
    transit inventory tracking, and automated stock movement postings.
    """
    __tablename__ = "stock_transfer_orders"

    transfer_no = Column(String(80), nullable=False, unique=True, index=True)
    source_branch_id = Column(String(50), nullable=False, index=True)
    source_store_name = Column(String(150), nullable=False)
    target_branch_id = Column(String(50), nullable=False, index=True)
    target_store_name = Column(String(150), nullable=False)
    transit_warehouse_id = Column(String(50), nullable=True)
    
    status = Column(String(30), nullable=False, default="DRAFT", index=True)
    # DRAFT | REQUESTED | APPROVED | DISPATCHED | IN_TRANSIT | RECEIVED | REJECTED | CANCELLED
    
    transfer_date = Column(Date, nullable=False, default=date.today)
    expected_arrival_date = Column(Date, nullable=True)
    
    total_line_items = Column(Integer, default=0)
    total_requested_qty = Column(Numeric(12, 4), default=0.0000)
    total_shipped_qty = Column(Numeric(12, 4), default=0.0000)
    total_received_qty = Column(Numeric(12, 4), default=0.0000)
    total_valuation = Column(Numeric(15, 2), default=0.00)
    
    requested_by = Column(String(50), nullable=True)
    approved_by = Column(String(50), nullable=True)
    dispatched_by = Column(String(50), nullable=True)
    received_by = Column(String(50), nullable=True)
    remarks = Column(Text, nullable=True)

    items = relationship("StockTransferOrderItem", back_populates="transfer_order", cascade="all, delete-orphan")


class StockTransferOrderItem(BaseEntity):
    """
    Individual SKU line items within a Stock Transfer Order.
    """
    __tablename__ = "stock_transfer_order_items"

    transfer_order_id = Column(String(50), ForeignKey("stock_transfer_orders.id", ondelete="CASCADE"), nullable=False, index=True)
    product_id = Column(String(50), ForeignKey("products.id", ondelete="RESTRICT"), nullable=False, index=True)
    
    sku = Column(String(50), nullable=False)
    product_name = Column(String(255), nullable=False)
    
    requested_qty = Column(Numeric(12, 4), nullable=False, default=0.0000)
    approved_qty = Column(Numeric(12, 4), nullable=False, default=0.0000)
    shipped_qty = Column(Numeric(12, 4), nullable=False, default=0.0000)
    received_qty = Column(Numeric(12, 4), nullable=False, default=0.0000)
    
    unit_cost = Column(Numeric(15, 2), nullable=False, default=0.00)
    total_valuation = Column(Numeric(15, 2), nullable=False, default=0.00)
    notes = Column(Text, nullable=True)

    transfer_order = relationship("StockTransferOrder", back_populates="items")


class StockRebalancingRecommendation(BaseEntity):
    """
    Automated inventory redistribution recommendations generated by velocity algorithm.
    """
    __tablename__ = "stock_rebalancing_recommendations"

    source_branch_id = Column(String(50), nullable=False, index=True)
    target_branch_id = Column(String(50), nullable=False, index=True)
    product_id = Column(String(50), ForeignKey("products.id", ondelete="RESTRICT"), nullable=False, index=True)
    sku = Column(String(50), nullable=False)
    product_name = Column(String(255), nullable=False)
    
    source_stock_on_hand = Column(Numeric(12, 4), nullable=False, default=0.0000)
    target_stock_on_hand = Column(Numeric(12, 4), nullable=False, default=0.0000)
    recommended_qty = Column(Numeric(12, 4), nullable=False, default=0.0000)
    
    reason = Column(String(255), nullable=False) # SURPLUS_REDISTRIBUTION | STOCKOUT_PREVENTION | MIN_MAX_ALIGNMENT
    status = Column(String(30), default="PENDING", index=True) # PENDING | CONVERTED | DISMISSED

    transfer_order_id = Column(String(50), ForeignKey("stock_transfer_orders.id", ondelete="SET NULL"), nullable=True)
