# Project      : SMRITI Retail OS
# Organization : SmritiSys
# Author       : Jawahar Ramkripal Mallah
# Copyright    : © SMRITIBooks.com. All Rights Reserved.
# Production Nginx Config with SSL Termination & Reverse Proxy (AOP-005)

user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    upstream backend_api {
        server smriti-api-prod:8000;
    }

    upstream frontend_workspace {
        server smriti-workspace-prod:3000;
    }

    server {
        listen 80;
        server_name workspace.smritisys.com api.smritisys.com;

        location / {
            proxy_pass http://frontend_workspace;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://backend_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
