"""
Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Designation  : Chief Systems Architect & Creator
Email        : support@smritibooks.com
Websites     : smritisys.com | smritibooks.com | erpnbook.com | aitdl.com
Version      : 4.13.0
Created      : 2026-07-20
Modified     : 2026-07-20
Copyright    : (c) SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software
"""

"""
SMRITI Indian Compliance Core Layer (ICCL) - GSTR-2B Reconciliation Engine

GSTR-2B is the auto-drafted ITC (Input Tax Credit) statement generated by the
GST portal on the 14th of every month, reflecting all B2B invoices filed by
suppliers in GSTR-1 / IFF for the previous month.

This engine reconciles:
1. Invoices claimed in books (purchase register) against GSTR-2B data
2. Detects: vendor GSTIN mismatches, ITC amount mismatches, missing invoices
3. Classifies ITC as: Eligible, Ineligible, Blocked (Section 17(5)), Mismatched
4. Generates actionable reconciliation report with per-invoice discrepancy details

SMRITI Error Codes:
  SMRITI-GSTR2B-001: Invoice in books but missing in GSTR-2B
  SMRITI-GSTR2B-002: Invoice in GSTR-2B but not in books
  SMRITI-GSTR2B-003: ITC amount mismatch (books vs GSTR-2B)
  SMRITI-GSTR2B-004: Supplier GSTIN mismatch
  SMRITI-GSTR2B-005: Ineligible ITC (blocked under Section 17(5))
"""

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import Optional


class ITCStatus(str, Enum):
    MATCHED = "MATCHED"
    BOOKS_ONLY = "BOOKS_ONLY"           # In purchase register, not in GSTR-2B
    GSTR2B_ONLY = "GSTR2B_ONLY"        # In GSTR-2B, not in books
    ITC_MISMATCH = "ITC_MISMATCH"      # Both present but amounts differ
    GSTIN_MISMATCH = "GSTIN_MISMATCH"  # Supplier GSTIN differs
    INELIGIBLE = "INELIGIBLE"          # Section 17(5) blocked credit


class IneligibleITCReason(str, Enum):
    """Section 17(5) of CGST Act — Blocked Credits"""
    MOTOR_VEHICLE = "Motor vehicle for personal use (Sec 17(5)(a))"
    FOOD_BEVERAGE = "Food, beverages, outdoor catering (Sec 17(5)(b))"
    BEAUTY_HEALTH = "Beauty treatment, health services, cosmetic surgery (Sec 17(5)(b))"
    CLUB_MEMBERSHIP = "Membership of club/health/fitness centre (Sec 17(5)(b))"
    RENT_A_CAB = "Rent-a-cab, life/health insurance unless mandatory (Sec 17(5)(b))"
    TRAVEL_BENEFITS = "Travel benefits to employees (Sec 17(5)(b))"
    CONSTRUCTION = "Works contract for construction of immovable property (Sec 17(5)(c))"
    PERSONAL_CONSUMPTION = "Goods/services for personal consumption (Sec 17(5)(g))"
    FREE_SAMPLES = "Goods disposed of as gifts or free samples (Sec 17(5)(h))"


@dataclass
class BookInvoice:
    """An invoice as recorded in the buyer's purchase register."""
    invoice_number: str
    supplier_gstin: str
    invoice_date: str             # ISO date string
    taxable_value: Decimal
    igst: Decimal
    cgst: Decimal
    sgst: Decimal
    itc_claimed: Decimal          # Total ITC claimed (igst + cgst + sgst)
    is_rcm: bool = False          # Reverse Charge Mechanism
    ineligible_reason: Optional[IneligibleITCReason] = None


@dataclass
class GSTR2BInvoice:
    """An invoice as appearing in GSTR-2B (auto-drafted by GST portal)."""
    invoice_number: str
    supplier_gstin: str
    invoice_date: str
    taxable_value: Decimal
    igst: Decimal
    cgst: Decimal
    sgst: Decimal
    itc_available: Decimal        # ITC available as per GSTR-2B
    filing_status: str = "FILED"  # FILED / PENDING / CANCELLED


@dataclass
class ReconciliationItem:
    """Result of reconciling one invoice pair."""
    invoice_number: str
    status: ITCStatus
    error_code: str
    book_invoice: Optional[BookInvoice]
    gstr2b_invoice: Optional[GSTR2BInvoice]
    itc_claimed: Decimal
    itc_available: Decimal
    difference: Decimal           # itc_available - itc_claimed (positive = extra, negative = short)
    actionable_message: str
    is_ineligible: bool = False
    ineligible_reason: Optional[IneligibleITCReason] = None


@dataclass
class GSTR2BReconciliationReport:
    """Full reconciliation report for a filing period."""
    tenant_id: str
    filing_period: str            # e.g. "2026-06" (YYYY-MM)
    total_invoices_in_books: int
    total_invoices_in_gstr2b: int
    matched: int
    books_only: int               # Missing from GSTR-2B — ITC at risk
    gstr2b_only: int              # Not in books — possibly missed invoices
    itc_mismatch: int
    gstin_mismatch: int
    ineligible: int
    total_itc_claimed: Decimal
    total_itc_available: Decimal
    itc_net_difference: Decimal   # available - claimed
    items: list[ReconciliationItem] = field(default_factory=list)
    summary_message: str = ""


def reconcile_gstr2b(
    tenant_id: str,
    filing_period: str,
    book_invoices: list[BookInvoice],
    gstr2b_invoices: list[GSTR2BInvoice],
) -> GSTR2BReconciliationReport:
    """
    Reconcile purchase register invoices against GSTR-2B data.

    Args:
        tenant_id: Tenant/company identifier
        filing_period: Period in YYYY-MM format (e.g. "2026-06")
        book_invoices: Invoices from the buyer's purchase register
        gstr2b_invoices: Invoices from the GSTR-2B statement

    Returns:
        GSTR2BReconciliationReport with per-invoice reconciliation items
    """
    # Build lookup maps by invoice number (case-insensitive normalized)
    def normalize(inv_no: str) -> str:
        return inv_no.strip().upper().replace(" ", "").replace("/", "").replace("-", "")

    books_map: dict[str, BookInvoice] = {
        normalize(b.invoice_number): b for b in book_invoices
    }
    gstr2b_map: dict[str, GSTR2BInvoice] = {
        normalize(g.invoice_number): g for g in gstr2b_invoices
    }

    all_keys = set(books_map) | set(gstr2b_map)
    items: list[ReconciliationItem] = []

    for key in all_keys:
        book = books_map.get(key)
        g2b = gstr2b_map.get(key)

        if book and g2b:
            # Both present — check for mismatches
            if book.supplier_gstin.upper() != g2b.supplier_gstin.upper():
                items.append(ReconciliationItem(
                    invoice_number=book.invoice_number,
                    status=ITCStatus.GSTIN_MISMATCH,
                    error_code="SMRITI-GSTR2B-004",
                    book_invoice=book,
                    gstr2b_invoice=g2b,
                    itc_claimed=book.itc_claimed,
                    itc_available=g2b.itc_available,
                    difference=g2b.itc_available - book.itc_claimed,
                    actionable_message=(
                        f"Supplier GSTIN mismatch for invoice {book.invoice_number}: "
                        f"Books={book.supplier_gstin}, GSTR-2B={g2b.supplier_gstin}. "
                        "Verify with supplier and correct purchase entry."
                    ),
                ))
            elif book.ineligible_reason:
                items.append(ReconciliationItem(
                    invoice_number=book.invoice_number,
                    status=ITCStatus.INELIGIBLE,
                    error_code="SMRITI-GSTR2B-005",
                    book_invoice=book,
                    gstr2b_invoice=g2b,
                    itc_claimed=book.itc_claimed,
                    itc_available=g2b.itc_available,
                    difference=Decimal("0"),
                    actionable_message=(
                        f"ITC on invoice {book.invoice_number} is ineligible: "
                        f"{book.ineligible_reason.value}. "
                        "Reverse this ITC claim immediately to avoid interest."
                    ),
                    is_ineligible=True,
                    ineligible_reason=book.ineligible_reason,
                ))
            elif abs(book.itc_claimed - g2b.itc_available) > Decimal("1"):
                # Amount mismatch beyond Rs 1 rounding tolerance
                items.append(ReconciliationItem(
                    invoice_number=book.invoice_number,
                    status=ITCStatus.ITC_MISMATCH,
                    error_code="SMRITI-GSTR2B-003",
                    book_invoice=book,
                    gstr2b_invoice=g2b,
                    itc_claimed=book.itc_claimed,
                    itc_available=g2b.itc_available,
                    difference=g2b.itc_available - book.itc_claimed,
                    actionable_message=(
                        f"ITC mismatch on invoice {book.invoice_number}: "
                        f"Claimed Rs {book.itc_claimed}, Available Rs {g2b.itc_available}. "
                        f"Difference: Rs {g2b.itc_available - book.itc_claimed:+.2f}. "
                        "Contact supplier to amend GSTR-1 or correct purchase entry."
                    ),
                ))
            else:
                items.append(ReconciliationItem(
                    invoice_number=book.invoice_number,
                    status=ITCStatus.MATCHED,
                    error_code="",
                    book_invoice=book,
                    gstr2b_invoice=g2b,
                    itc_claimed=book.itc_claimed,
                    itc_available=g2b.itc_available,
                    difference=g2b.itc_available - book.itc_claimed,
                    actionable_message="Invoice matched. ITC is eligible for claim.",
                ))

        elif book and not g2b:
            # In books but missing from GSTR-2B — supplier may not have filed
            items.append(ReconciliationItem(
                invoice_number=book.invoice_number,
                status=ITCStatus.BOOKS_ONLY,
                error_code="SMRITI-GSTR2B-001",
                book_invoice=book,
                gstr2b_invoice=None,
                itc_claimed=book.itc_claimed,
                itc_available=Decimal("0"),
                difference=-book.itc_claimed,
                actionable_message=(
                    f"Invoice {book.invoice_number} is in your purchase register "
                    f"but NOT in GSTR-2B. Supplier {book.supplier_gstin} may not have "
                    "filed GSTR-1 for this period. "
                    "Follow up with supplier or defer ITC claim to next month."
                ),
            ))

        else:  # g2b only
            # In GSTR-2B but not in books — missed invoice entry
            items.append(ReconciliationItem(
                invoice_number=g2b.invoice_number,
                status=ITCStatus.GSTR2B_ONLY,
                error_code="SMRITI-GSTR2B-002",
                book_invoice=None,
                gstr2b_invoice=g2b,
                itc_claimed=Decimal("0"),
                itc_available=g2b.itc_available,
                difference=g2b.itc_available,
                actionable_message=(
                    f"Invoice {g2b.invoice_number} from supplier {g2b.supplier_gstin} "
                    "appears in GSTR-2B but is not recorded in your purchase register. "
                    f"Potential missed ITC of Rs {g2b.itc_available}. "
                    "Verify physical invoice receipt and record the purchase entry."
                ),
            ))

    # Compute summary totals
    matched = sum(1 for i in items if i.status == ITCStatus.MATCHED)
    books_only = sum(1 for i in items if i.status == ITCStatus.BOOKS_ONLY)
    gstr2b_only = sum(1 for i in items if i.status == ITCStatus.GSTR2B_ONLY)
    itc_mismatch = sum(1 for i in items if i.status == ITCStatus.ITC_MISMATCH)
    gstin_mismatch = sum(1 for i in items if i.status == ITCStatus.GSTIN_MISMATCH)
    ineligible = sum(1 for i in items if i.status == ITCStatus.INELIGIBLE)
    total_claimed = sum(i.itc_claimed for i in items)
    total_available = sum(i.itc_available for i in items)
    net_diff = total_available - total_claimed

    issues = books_only + gstr2b_only + itc_mismatch + gstin_mismatch + ineligible
    if issues == 0:
        summary = f"Full reconciliation complete. All {matched} invoices matched. ITC eligible: Rs {total_claimed:,.2f}."
    else:
        summary = (
            f"Reconciliation found {issues} issue(s): "
            f"{books_only} missing from GSTR-2B, {gstr2b_only} not in books, "
            f"{itc_mismatch} ITC mismatches, {gstin_mismatch} GSTIN mismatches, "
            f"{ineligible} ineligible. "
            f"Net ITC difference: Rs {net_diff:+,.2f}."
        )

    return GSTR2BReconciliationReport(
        tenant_id=tenant_id,
        filing_period=filing_period,
        total_invoices_in_books=len(book_invoices),
        total_invoices_in_gstr2b=len(gstr2b_invoices),
        matched=matched,
        books_only=books_only,
        gstr2b_only=gstr2b_only,
        itc_mismatch=itc_mismatch,
        gstin_mismatch=gstin_mismatch,
        ineligible=ineligible,
        total_itc_claimed=total_claimed,
        total_itc_available=total_available,
        itc_net_difference=net_diff,
        items=items,
        summary_message=summary,
    )
