"""
Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Designation  : Chief Systems Architect & Creator
Email        : support@smritibooks.com
Websites     : smritibooks.com | erpnbook.com | aitdl.com
Version      : 3.33.0
Created      : 2026-10-09
Modified     : 2026-10-09
Copyright    : © SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software
Classification: Master Registry Presets Service
"""

from typing import Dict, List, Any, Optional

STANDARD_LOOKUP_PRESETS: Dict[str, List[Dict[str, Any]]] = {
    "department": [
        {"code": "MENSWEAR", "name": "Menswear", "description": "Men's Apparel, Denim, Outerwear & Essentials"},
        {"code": "WOMENSWEAR", "name": "Womenswear", "description": "Women's Western, Ethnic, Dresses & Casuals"},
        {"code": "FOOTWEAR_DEPT", "name": "Footwear & Shoes", "description": "Men's, Women's & Kids' Footwear"},
        {"code": "KIDSWEAR", "name": "Kidswear & Infants", "description": "Boys, Girls, Infants & Toddlers"},
        {"code": "ACCESSORIES_DEPT", "name": "Fashion Accessories", "description": "Bags, Belts, Wallets, Caps & Small Goods"},
        {"code": "BILLING_POS", "name": "Front Desk & Billing", "description": "Cash counters, POS registers & Returns counter"},
        {"code": "LOGISTICS_WMS", "name": "Warehouse & Inward", "description": "GRN Inward, Barcoding, Stock & Logistics"},
        {"code": "FINANCE_ACCOUNTS", "name": "Accounts & Finance", "description": "Statutory, Ledger reconciliation & Tax compliance"},
        {"code": "CUSTOMER_CARE", "name": "Customer Experience", "description": "Customer Support, CRM, Loyalty & Exchanges"},
        {"code": "ADMIN_OPERATIONS", "name": "Store Operations", "description": "Store administration, security & facility"},
    ],
    "designation": [
        {"code": "STORE_MANAGER", "name": "Store General Manager", "description": "Overall retail store P&L and operations head"},
        {"code": "ASST_MANAGER", "name": "Assistant Store Manager", "description": "Floor operations, shift supervisor & reconciliation"},
        {"code": "CASHIER", "name": "Head Cashier & Billing Clerk", "description": "POS counter operations, cash drops & payment settlement"},
        {"code": "SALES_ASSOCIATE", "name": "Senior Sales Associate", "description": "Customer assistance, merchandising & retail floor sales"},
        {"code": "INVENTORY_SUPERVISOR", "name": "Inventory / Stock Supervisor", "description": "Physical audit, inward gate receipt & stock movements"},
        {"code": "MERCHANDISER", "name": "Retail Visual Merchandiser", "description": "Display management, assortment & planogram upkeep"},
        {"code": "AUDITOR", "name": "Internal Stock & Compliance Auditor", "description": "Discrepancy reconciliation & cycle count auditor"},
        {"code": "IT_EXECUTIVE", "name": "Systems & EDP Administrator", "description": "Barcode hardware, thermal printer & network support"},
    ],
    "bank": [
        {"code": "HDFC", "name": "HDFC Bank Current Account", "description": "Primary retail merchant settlement account"},
        {"code": "SBI", "name": "State Bank of India Corporate Account", "description": "Treasury, tax payments & statutory remittance"},
        {"code": "ICICI", "name": "ICICI Bank Current Account", "description": "EDC card swipe merchant current account"},
        {"code": "AXIS", "name": "Axis Bank Current Account", "description": "Secondary operating current account"},
        {"code": "KOTAK", "name": "Kotak Mahindra Bank Account", "description": "Vendor RTGS/NEFT disbursement account"},
        {"code": "PNB", "name": "Punjab National Bank Account", "description": "Institutional banking clearing account"},
    ],
    "payment_mode": [
        {"code": "CASH", "name": "Cash Payment", "description": "Physical currency tender deposited in cash drawer"},
        {"code": "UPI", "name": "UPI / QR Code", "description": "Unified Payments Interface (PhonePe, GPay, Paytm, BHIM)"},
        {"code": "CARD_CC", "name": "Credit Card (POS Swipe/Chip)", "description": "Visa, Mastercard, RuPay, Amex credit card swipe"},
        {"code": "CARD_DC", "name": "Debit Card (POS PIN/Tap)", "description": "Bank debit card PIN tap or EDC terminal swipe"},
        {"code": "NET_BANK", "name": "Net Banking / Direct Transfer", "description": "NEFT, RTGS or IMPS bank transfer"},
        {"code": "WALLET", "name": "Store Credit / Customer Wallet", "description": "Store credit refund balance or customer loyalty points"},
        {"code": "VOUCHER", "name": "Gift Voucher / Promo Coupon", "description": "Prepaid shopping card or authorized promotional gift voucher"},
        {"code": "CHEQUE", "name": "Bank Cheque", "description": "Institutional clearing cheque with drawer details"},
    ],
    "expense_category": [
        {"code": "STORE_RENT", "name": "Store Lease & Rent", "description": "Monthly commercial showroom lease payment"},
        {"code": "ELECTRICITY_UTILITY", "name": "Electricity & Power Utility", "description": "Commercial power bill, HVAC & diesel generator"},
        {"code": "FREIGHT_INWARD", "name": "Freight & Transporter Inward", "description": "Logistics charges, docket fees & courier inward"},
        {"code": "PACKAGING_MATERIAL", "name": "Packaging & Bags", "description": "Carry bags, thermal paper rolls, courier boxes & bubble wrap"},
        {"code": "STAFF_WELFARE", "name": "Staff Welfare & Tea", "description": "Staff refreshments, pantry expenses & team lunches"},
        {"code": "MARKETING_PROMO", "name": "Local Marketing & Signage", "description": "Hoardings, flyers, local ads & festival decorations"},
        {"code": "OFFICE_STATIONERY", "name": "Stationery & Consumables", "description": "A4 paper, tag fasteners, barcode ribbons & office pens"},
        {"code": "SOFTWARE_SUBS", "name": "Software & Telecom", "description": "Internet broadband, cloud hosting & SMS gateway balance"},
    ],
    "currency": [
        {"code": "INR", "name": "Indian Rupee (₹)", "description": "Primary functional currency (ISO 4217: INR)"},
        {"code": "USD", "name": "United States Dollar ($)", "description": "International trade standard (ISO 4217: USD)"},
        {"code": "EUR", "name": "Euro (€)", "description": "European single currency (ISO 4217: EUR)"},
        {"code": "GBP", "name": "British Pound Sterling (£)", "description": "United Kingdom currency (ISO 4217: GBP)"},
        {"code": "AED", "name": "United Arab Emirates Dirham (AED)", "description": "Middle East GCC currency (ISO 4217: AED)"},
    ],
    "gst_rate": [
        {"code": "GST_0", "name": "0% GST (Exempted)", "description": "Exempted basic staples, unwrapped goods and agricultural goods"},
        {"code": "GST_3", "name": "3% GST (Precious Metals)", "description": "Gold, silver, diamonds and precious jewellery"},
        {"code": "GST_5", "name": "5% GST (Essential Retail / Footwear < 1k)", "description": "Footwear & Apparel with sale value up to ₹1,000 per piece"},
        {"code": "GST_12", "name": "12% GST (Standard Apparel & Footwear > 1k)", "description": "Apparel & Footwear with sale value exceeding ₹1,000 per piece"},
        {"code": "GST_18", "name": "18% GST (Standard Services & Merchandise)", "description": "Fashion accessories, luggage, IT goods and commercial services"},
        {"code": "GST_28", "name": "28% GST (Luxury / High Tier)", "description": "Luxury watches, automobiles, air conditioning and sin goods"},
    ],
    "uom": [
        {"code": "PCS", "name": "Pieces (Pcs)", "description": "Individual single unit retail item"},
        {"code": "PAIR", "name": "Pair (Pr)", "description": "Two-piece unit (Footwear, socks, gloves)"},
        {"code": "BOX", "name": "Box (Bx)", "description": "Pre-packaged box containing multiple pieces"},
        {"code": "SET", "name": "Set (St)", "description": "Coordinated ensemble, suit set or combo pack"},
        {"code": "MTR", "name": "Meter (M)", "description": "Linear meter of fabric, ribbon or textile"},
        {"code": "KG", "name": "Kilogram (Kg)", "description": "Weight based mass measurement"},
        {"code": "DOZ", "name": "Dozen (Dz)", "description": "12 pieces per master pack"},
        {"code": "ROL", "name": "Roll (Rl)", "description": "Continuous roll of fabric, tape or thermal label"},
        {"code": "PKT", "name": "Packet (Pkt)", "description": "Sealed packet or pouch"},
    ],
    "gender": [
        {"code": "MEN", "name": "Men", "description": "Adult male footwear, apparel & grooming"},
        {"code": "WOMEN", "name": "Women", "description": "Adult female footwear, fashion & accessories"},
        {"code": "UNISEX", "name": "Unisex", "description": "Gender-neutral apparel, footwear & lifestyle goods"},
        {"code": "BOYS", "name": "Boys", "description": "Youth & boys collection (Age 4-14)"},
        {"code": "GIRLS", "name": "Girls", "description": "Youth & girls collection (Age 4-14)"},
        {"code": "INFANTS", "name": "Infants / Toddlers", "description": "Babywear & newborn (Age 0-3)"},
    ],
    "category": [
        {"code": "FOOTWEAR", "name": "Footwear", "description": "Formal, casual, sports and ethnic footwear"},
        {"code": "APPAREL", "name": "Apparel & Garments", "description": "Ready-to-wear shirts, denim, trousers and ethnic wear"},
        {"code": "ACCESSORIES", "name": "Fashion Accessories", "description": "Belts, wallets, ties, socks, caps & handkerchiefs"},
        {"code": "BAGS_LUGGAGE", "name": "Bags & Luggage", "description": "Backpacks, duffle bags, trolleys and office briefcases"},
        {"code": "CARE_MAINT", "name": "Care & Maintenance", "description": "Shoe polish, cleaning sprays, brushes and insoles"},
    ],
    "subcategory": [
        {"code": "CASUAL_WEAR", "name": "Casual Lifestyle", "description": "Daily comfortable wear and weekend styles"},
        {"code": "FORMAL_WEAR", "name": "Formal Professional", "description": "Office, executive and corporate wear"},
        {"code": "ETHNIC_WEAR", "name": "Ethnic & Festive", "description": "Traditional wedding, festive and cultural attire"},
        {"code": "SPORTS_ACTIVE", "name": "Sports & Athletics", "description": "Running, training, gym and outdoor performance"},
        {"code": "PARTY_WEAR", "name": "Party & Evening", "description": "High fashion, cocktail and celebration wear"},
        {"code": "LOUNGE_WEAR", "name": "Home & Loungewear", "description": "Sleepwear, pyjamas and relaxing casuals"},
    ],
    "product_type": [
        {"code": "SNEAKERS", "name": "Sneakers", "description": "Lifestyle & casual street sneakers"},
        {"code": "SPORTS_SHOES", "name": "Sports Shoes", "description": "Running, gym training & athletic shoes"},
        {"code": "FORMAL_SHOES", "name": "Formal Shoes", "description": "Derby, Oxford, monk strap & formal slip-ons"},
        {"code": "LOAFERS", "name": "Loafers", "description": "Penny, tassel & driving loafers"},
        {"code": "SANDALS", "name": "Sandals", "description": "Casual strap sandals, floaters & fisherman sandals"},
        {"code": "SLIPPERS", "name": "Slippers", "description": "Comfort house slippers & leather chappals"},
        {"code": "FLIP_FLOPS", "name": "Flip Flops", "description": "Beachwear & casual rubber/EVA flip-flops"},
        {"code": "BOOTS", "name": "Boots", "description": "Chelsea boots, ankle boots & rugged boots"},
        {"code": "HEELS", "name": "Heels", "description": "Pumps, court shoes & fashion heels"},
        {"code": "BELLIES", "name": "Bellies / Ballerinas", "description": "Flat ballet shoes & casual slip-on bellies"},
        {"code": "WEDGES", "name": "Wedges", "description": "Elevated wedge heel comfort sandals"},
        {"code": "CLOGS", "name": "Clogs", "description": "Lightweight perforated EVA slip-on clogs"},
        {"code": "SHIRT", "name": "Woven Shirt", "description": "Formal, semi-formal & casual woven shirts"},
        {"code": "TSHIRT", "name": "T-Shirt / Polo", "description": "Round neck, V-neck and collared polo tees"},
        {"code": "JEANS", "name": "Denim Jeans", "description": "Skinny, slim, regular and straight fit denim"},
        {"code": "TROUSERS", "name": "Trousers & Chinos", "description": "Formal trousers and cotton casual chinos"},
        {"code": "KURTA", "name": "Kurta", "description": "Short & long traditional ethnic kurtas"},
        {"code": "JACKET", "name": "Jacket / Blazer", "description": "Bomber jackets, windcheaters & blazers"},
    ],
    "color": [
        {"code": "BLACK", "name": "Black", "description": "Jet Black (#000000)"},
        {"code": "WHITE", "name": "White", "description": "Pure White (#FFFFFF)"},
        {"code": "NAVY", "name": "Navy Blue", "description": "Deep Navy Blue (#000080)"},
        {"code": "GREY", "name": "Grey", "description": "Classic Heather Grey (#808080)"},
        {"code": "CHARCOAL", "name": "Charcoal", "description": "Dark Charcoal Grey (#36454F)"},
        {"code": "BROWN", "name": "Brown", "description": "Rich Coffee Brown (#654321)"},
        {"code": "TAN", "name": "Tan", "description": "Warm Natural Tan (#D2B48C)"},
        {"code": "BEIGE", "name": "Beige", "description": "Subtle Beige Sand (#F5F5DC)"},
        {"code": "RED", "name": "Red", "description": "Crimson Red (#FF0000)"},
        {"code": "MAROON", "name": "Maroon", "description": "Deep Royal Maroon (#800000)"},
        {"code": "BLUE", "name": "Royal Blue", "description": "Vibrant Royal Blue (#4169E1)"},
        {"code": "OLIVE", "name": "Olive Green", "description": "Military Olive Green (#808000)"},
        {"code": "GREEN", "name": "Forest Green", "description": "Deep Emerald Forest Green (#228B22)"},
        {"code": "YELLOW", "name": "Mustard Yellow", "description": "Warm Mustard Gold (#FFDB58)"},
        {"code": "ORANGE", "name": "Orange", "description": "Burnt Orange (#CC5500)"},
        {"code": "PINK", "name": "Pink", "description": "Soft Blush Pink (#FFC0CB)"},
        {"code": "LAVENDER", "name": "Lavender", "description": "Pastel Lavender (#E6E6FA)"},
        {"code": "GOLD", "name": "Gold", "description": "Metallic Gold (#FFD700)"},
        {"code": "SILVER", "name": "Silver", "description": "Metallic Silver (#C0C0C0)"},
    ],
    "size": [
        {"code": "UK_5", "name": "UK 5 (Euro 38)", "description": "Footwear size UK/IND 5 (Euro 38)"},
        {"code": "UK_6", "name": "UK 6 (Euro 39-40)", "description": "Footwear size UK/IND 6 (Euro 39-40)"},
        {"code": "UK_7", "name": "UK 7 (Euro 41)", "description": "Footwear size UK/IND 7 (Euro 41)"},
        {"code": "UK_8", "name": "UK 8 (Euro 42)", "description": "Footwear size UK/IND 8 (Euro 42)"},
        {"code": "UK_9", "name": "UK 9 (Euro 43)", "description": "Footwear size UK/IND 9 (Euro 43)"},
        {"code": "UK_10", "name": "UK 10 (Euro 44)", "description": "Footwear size UK/IND 10 (Euro 44)"},
        {"code": "UK_11", "name": "UK 11 (Euro 45)", "description": "Footwear size UK/IND 11 (Euro 45)"},
        {"code": "UK_12", "name": "UK 12 (Euro 46)", "description": "Footwear size UK/IND 12 (Euro 46)"},
        {"code": "SZ_XS", "name": "Extra Small (XS)", "description": "Apparel chest 34-36 inches"},
        {"code": "SZ_S", "name": "Small (S)", "description": "Apparel chest 38 inches"},
        {"code": "SZ_M", "name": "Medium (M)", "description": "Apparel chest 40 inches"},
        {"code": "SZ_L", "name": "Large (L)", "description": "Apparel chest 42 inches"},
        {"code": "SZ_XL", "name": "Extra Large (XL)", "description": "Apparel chest 44 inches"},
        {"code": "SZ_XXL", "name": "Double XL (XXL)", "description": "Apparel chest 46 inches"},
        {"code": "SZ_3XL", "name": "Triple XL (3XL)", "description": "Apparel chest 48 inches"},
        {"code": "WAIST_28", "name": "Waist 28\"", "description": "Bottomwear waist size 28 inches"},
        {"code": "WAIST_30", "name": "Waist 30\"", "description": "Bottomwear waist size 30 inches"},
        {"code": "WAIST_32", "name": "Waist 32\"", "description": "Bottomwear waist size 32 inches"},
        {"code": "WAIST_34", "name": "Waist 34\"", "description": "Bottomwear waist size 34 inches"},
        {"code": "WAIST_36", "name": "Waist 36\"", "description": "Bottomwear waist size 36 inches"},
        {"code": "WAIST_38", "name": "Waist 38\"", "description": "Bottomwear waist size 38 inches"},
    ],
    "heel_type": [
        {"code": "FLAT", "name": "Flat", "description": "Zero elevation ergonomic flat sole"},
        {"code": "BLOCK", "name": "Block Heel", "description": "Broad rectangular supportive heel"},
        {"code": "WEDGE", "name": "Wedge", "description": "Continuous solid supportive wedge heel"},
        {"code": "STILETTO", "name": "Stiletto", "description": "Slim needle stiletto evening heel"},
        {"code": "KITTEN", "name": "Kitten Heel", "description": "Low slender heel (1.5 to 2 inches)"},
        {"code": "PLATFORM", "name": "Platform", "description": "Thick elevated platform base with heel"},
        {"code": "CONE", "name": "Cone Heel", "description": "Broad at base tapering downward"},
    ],
    "upper_material": [
        {"code": "GENUINE_LEATHER", "name": "Genuine Leather", "description": "Premium full grain and top grain animal hide"},
        {"code": "SYNTHETIC_PU", "name": "Synthetic PU", "description": "Durable polyurethane leatherette finish"},
        {"code": "CANVAS", "name": "Cotton Canvas", "description": "Breathable natural heavy cotton weave"},
        {"code": "MESH", "name": "Engineered Mesh", "description": "High-airflow sports & running textile"},
        {"code": "SUEDE", "name": "Suede Leather", "description": "Soft velvety napped leather texture"},
        {"code": "PVC", "name": "PVC Synthetic", "description": "Waterproof synthetic polymer"},
        {"code": "PATENT", "name": "Patent Leather", "description": "High-gloss lacquered reflective leather"},
        {"code": "FABRIC", "name": "Textured Fabric", "description": "Jacquard, knit or denim fabric upper"},
    ],
    "outsole_material": [
        {"code": "TPR", "name": "TPR (Thermo Plastic Rubber)", "description": "High slip-resistance and flexible rubber compound"},
        {"code": "RUBBER", "name": "Vulcanized Rubber", "description": "Durable heavy-duty vulcanized natural rubber"},
        {"code": "EVA", "name": "EVA (Ethylene-Vinyl Acetate)", "description": "Featherlight shock-absorbing molded foam"},
        {"code": "PHYLON", "name": "Phylon Foam", "description": "Compression-molded resilient athletic midsole"},
        {"code": "PU_SOLE", "name": "Polyurethane Sole", "description": "Lightweight, long-lasting industrial and casual PU"},
        {"code": "AIR_MIX", "name": "Air Mix Compound", "description": "Budget lightweight daily wear compound"},
        {"code": "LEATHER_SOLE", "name": "Natural Sole Leather", "description": "Traditional luxury handcrafted formal shoe sole"},
    ],
    "collection_type": [
        {"code": "CORE_ANNUAL", "name": "Core Essentials (All-Year)", "description": "Perennial fast-moving stock carried throughout year"},
        {"code": "SPRING_SUMMER", "name": "Spring / Summer (SS)", "description": "Lightweight, breathable and pastel seasonal collection"},
        {"code": "AUTUMN_WINTER", "name": "Autumn / Winter (AW)", "description": "Warm, layered, boots and festive deep tone collection"},
        {"code": "FESTIVE_SPECIAL", "name": "Festive & Wedding", "description": "Diwali, Eid, wedding and celebratory merchandise"},
        {"code": "SPORTS_ACTIVE", "name": "Active Athletics", "description": "Year-round running, gym and fitness merchandise"},
    ],
    "size_group": [
        {
            "code": "MEN_FOOTWEAR_UK_6_10",
            "name": "Men Footwear UK 6-10",
            "description": "Standard adult men footwear curve: UK 6, 7, 8, 9, 10",
            "category": "footwear",
            "values": ["UK-6", "UK-7", "UK-8", "UK-9", "UK-10"],
            "data": {"dimension": "size", "category": "footwear", "values": ["UK-6", "UK-7", "UK-8", "UK-9", "UK-10"]},
        },
        {
            "code": "WOMEN_FOOTWEAR_UK_3_7",
            "name": "Women Footwear UK 3-7",
            "description": "Standard adult women footwear curve: UK 3, 4, 5, 6, 7",
            "category": "footwear",
            "values": ["UK-3", "UK-4", "UK-5", "UK-6", "UK-7"],
            "data": {"dimension": "size", "category": "footwear", "values": ["UK-3", "UK-4", "UK-5", "UK-6", "UK-7"]},
        },
        {
            "code": "KIDS_FOOTWEAR_UK_10_2",
            "name": "Kids Footwear UK 10-2",
            "description": "Kids primary school curve: UK 10, 11, 12, 13, 1, 2",
            "category": "footwear",
            "values": ["UK-10", "UK-11", "UK-12", "UK-13", "UK-1", "UK-2"],
            "data": {"dimension": "size", "category": "footwear", "values": ["UK-10", "UK-11", "UK-12", "UK-13", "UK-1", "UK-2"]},
        },
        {
            "code": "APPAREL_ADULT_S_XXL",
            "name": "Apparel Adult S-XXL",
            "description": "Core garment size range: S, M, L, XL, XXL",
            "category": "apparel",
            "values": ["S", "M", "L", "XL", "XXL"],
            "data": {"dimension": "size", "category": "apparel", "values": ["S", "M", "L", "XL", "XXL"]},
        },
        {
            "code": "MEN_BOTTOMS_28_38",
            "name": "Men Bottoms 28-38",
            "description": "Denim & trouser waist curve: 28, 30, 32, 34, 36, 38",
            "category": "apparel",
            "values": ["28", "30", "32", "34", "36", "38"],
            "data": {"dimension": "size", "category": "apparel", "values": ["28", "30", "32", "34", "36", "38"]},
        },
    ],
    "color_group": [
        {
            "code": "MONOCHROME",
            "name": "Monochrome Essentials",
            "description": "Classic neutral wardrobe foundations",
            "category": "color",
            "values": ["BLACK", "WHITE", "GREY", "CHARCOAL"],
            "data": {"dimension": "color", "category": "color", "values": ["BLACK", "WHITE", "GREY", "CHARCOAL"]},
        },
        {
            "code": "EARTH_TONES",
            "name": "Earth & Rustic Tones",
            "description": "Warm nature-inspired leather and casual colors",
            "category": "color",
            "values": ["BROWN", "TAN", "BEIGE", "OLIVE"],
            "data": {"dimension": "color", "category": "color", "values": ["BROWN", "TAN", "BEIGE", "OLIVE"]},
        },
        {
            "code": "BOLD_PRIMARIES",
            "name": "Core Primaries",
            "description": "High-contrast sportswear and statement shades",
            "category": "color",
            "values": ["RED", "ROYAL BLUE", "NAVY", "FOREST GREEN"],
            "data": {"dimension": "color", "category": "color", "values": ["RED", "ROYAL BLUE", "NAVY", "FOREST GREEN"]},
        },
        {
            "code": "PASTELS",
            "name": "Soft Pastels",
            "description": "Subtle spring-summer and babywear hues",
            "category": "color",
            "values": ["PINK", "LAVENDER", "MINT", "PEACH"],
            "data": {"dimension": "color", "category": "color", "values": ["PINK", "LAVENDER", "MINT", "PEACH"]},
        },
    ],
    "po_cancel_reason": [
        {"code": "SUPPLIER_OUT_OF_STOCK", "name": "Supplier Out of Stock", "description": "Vendor factory unable to fulfill requested style quantities"},
        {"code": "COST_PRICE_MISMATCH", "name": "Cost Price Mismatch", "description": "Invoice rates deviate from approved procurement purchase order"},
        {"code": "DELIVERY_DELAYED", "name": "Breached Delivery Timeline", "description": "Shipment lead time exceeded without prior extension approval"},
        {"code": "NON_COMPLIANT_VENDOR", "name": "Statutory / GST Non-Compliance", "description": "Supplier GST status suspended or missing statutory e-Way bill"},
        {"code": "DUPLICATE_ORDER", "name": "Duplicate Purchase Order", "description": "Accidental duplicate order generated by branch or buyer"},
        {"code": "STORE_STRATEGY_CHANGE", "name": "Assortment Strategy Revision", "description": "Planogram revised; requisition discontinued by category head"},
    ],
    "po_cross_vendor_reason": [
        {"code": "BETTER_COMMERCIAL_TERMS", "name": "Favorable Wholesale Terms", "description": "Alternate supplier offering advantageous credit period or pricing"},
        {"code": "AUTHORIZED_OEM_DIRECT", "name": "Direct Brand Allocation", "description": "Purchasing direct from OEM distributor rather than regional broker"},
        {"code": "STOCK_OUT_EMERGENCY", "name": "Critical Stock-out Replacement", "description": "Emergency stock fulfillment to avert retail stock-out during campaign"},
    ],
}


def get_standard_lookup_presets(type_code: str) -> List[Dict[str, Any]]:
    """Retrieve standard recommendations for a given lookup type code from the authoritative registry."""
    if not type_code:
        return []
    normalized = type_code.strip().lower()
    return STANDARD_LOOKUP_PRESETS.get(normalized, [])
