"""
Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Designation  : Chief Systems Architect & Creator
Email        : support@smritibooks.com
Websites     : smritibooks.com | erpnbook.com | aitdl.com
Version      : 3.35.0
Created      : 2026-08-28
Modified     : 2026-08-28
Copyright    : © SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software
Classification: Internal

SMRITI Reporting & BI Engine — Master Canonical Report Registry Seed Catalog.
Enforces Invariant 1: Single Source of Truth for all 21 Canonical Reports.
Enforces Invariant 3: Shoper 9 aliases isolated to metadata adapter.
"""

from typing import Dict, List
from ..schemas.report_registry import ReportRegistryEntry, StudioType, ReportContractStatus

CANONICAL_REPORT_REGISTRY: Dict[str, ReportRegistryEntry] = {
    # =========================================================================
    # 1. SALES & CASHIER STUDIO
    # =========================================================================
    "RPT-SAL-001": ReportRegistryEntry(
        report_id="RPT-SAL-001",
        name="Daily Sales Summary Register",
        studio=StudioType.SALES_STUDIO,
        description="Comprehensive daily cashier collections, tenders, hourly sales velocity, and cash float reconciliation.",
        dimensions=["branch_id", "date", "cashier_id", "tender_type", "hour_of_day"],
        measures=["MTR_GROSS_SALES", "MTR_LINE_DISCOUNT", "MTR_HEADER_CONCESSION", "MTR_NET_SALES", "MTR_INVOICE_COUNT", "MTR_UNITS_SOLD"],
        allowed_roles=["CASHIER", "STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/sales/invoices",
        shoper_aliases=["411", "SR213600", "423", "SR209500"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-TAX-002": ReportRegistryEntry(
        report_id="RPT-TAX-002",
        name="Bill-wise Sales Register",
        studio=StudioType.SALES_STUDIO,
        description="Detailed chronological invoice register detailing gross sales, concessions, net revenue, and tender breakdown.",
        dimensions=["branch_id", "invoice_no", "date", "customer_id", "payment_mode", "cashier_id"],
        measures=["MTR_GROSS_SALES", "MTR_LINE_DISCOUNT", "MTR_HEADER_CONCESSION", "MTR_NET_SALES", "MTR_TAX_TOTAL"],
        allowed_roles=["CASHIER", "STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/sales/invoice-detail",
        shoper_aliases=["412", "SR202400"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-TAX-005": ReportRegistryEntry(
        report_id="RPT-TAX-005",
        name="Bill-wise Items Detail",
        studio=StudioType.SALES_STUDIO,
        description="Granular line-item breakdown showing item code, barcode, quantity, rate, discount, GST %, and line net.",
        dimensions=["branch_id", "invoice_no", "item_code", "barcode", "hsn_code", "category", "brand"],
        measures=["MTR_UNITS_SOLD", "MTR_LINE_DISCOUNT", "MTR_NET_SALES", "MTR_TAX_TOTAL"],
        allowed_roles=["CASHIER", "STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/inventory/item-master",
        shoper_aliases=["415", "SR202000"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-TAX-003": ReportRegistryEntry(
        report_id="RPT-TAX-003",
        name="Item-wise Sales Breakdown",
        studio=StudioType.SALES_STUDIO,
        description="Aggregated merchandise sales volume and turnover grouped by Item, HSN code, Brand, or Department.",
        dimensions=["branch_id", "item_code", "hsn_code", "category", "brand", "size", "color"],
        measures=["MTR_UNITS_SOLD", "MTR_GROSS_SALES", "MTR_LINE_DISCOUNT", "MTR_NET_SALES"],
        allowed_roles=["CASHIER", "STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/sales/item-sales-history",
        shoper_aliases=["413", "SR202200"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-SAL-004": ReportRegistryEntry(
        report_id="RPT-SAL-004",
        name="Salesperson Performance Index",
        studio=StudioType.SALES_STUDIO,
        description="Salesperson performance tracking bills cut, gross revenue, items per ticket, and target achievement.",
        dimensions=["branch_id", "salesperson_id", "salesperson_name", "date_range"],
        measures=["MTR_INVOICE_COUNT", "MTR_UNITS_SOLD", "MTR_NET_SALES", "MTR_ABV", "MTR_UPT"],
        allowed_roles=["STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/staff/performance",
        shoper_aliases=["419", "SR210000", "426", "SR221600"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),

    # =========================================================================
    # 2. MERCHANDISE & MATRIX STUDIO
    # =========================================================================
    "RPT-MRC-001": ReportRegistryEntry(
        report_id="RPT-MRC-001",
        name="Attribute + Size Merchandise Matrix",
        studio=StudioType.MERCHANDISE_STUDIO,
        description="Dynamic Size x Color matrix pivot across Brands, Categories, and Article codes for lifestyle/apparel retail.",
        dimensions=["brand", "department", "category", "article_code", "color", "size"],
        measures=["MTR_UNITS_SOLD", "MTR_NET_SALES", "MTR_STOCK_ON_HAND_QTY"],
        allowed_roles=["STORE_MANAGER", "MERCHANDISER", "ADMIN", "CEO"],
        drill_route="/merchandise/matrix-explorer",
        shoper_aliases=["422", "SR236300"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-SAL-003": ReportRegistryEntry(
        report_id="RPT-SAL-003",
        name="Top Selling Products Ledger",
        studio=StudioType.MERCHANDISE_STUDIO,
        description="Ranked top-selling articles by revenue, quantity sold, and gross margin contribution.",
        dimensions=["ranking", "item_code", "item_name", "category", "brand"],
        measures=["MTR_UNITS_SOLD", "MTR_NET_SALES", "MTR_GROSS_MARGIN_PCT"],
        allowed_roles=["STORE_MANAGER", "MERCHANDISER", "ADMIN", "CEO"],
        drill_route="/inventory/item-master",
        shoper_aliases=["418", "SR209600"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-MRC-002": ReportRegistryEntry(
        report_id="RPT-MRC-002",
        name="Category & Department Breakdown",
        studio=StudioType.MERCHANDISE_STUDIO,
        description="Superclass and category contribution breakdown analyzing sales and inventory share.",
        dimensions=["division", "department", "category", "sub_category", "brand"],
        measures=["MTR_UNITS_SOLD", "MTR_NET_SALES", "MTR_STOCK_ON_HAND_QTY", "MTR_SELL_THROUGH_PCT"],
        allowed_roles=["STORE_MANAGER", "MERCHANDISER", "ADMIN", "CEO"],
        drill_route="/merchandise/category-sales",
        shoper_aliases=["477", "SR216000"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-INV-003": ReportRegistryEntry(
        report_id="RPT-INV-003",
        name="Fast / Slow / Non-Moving Velocity",
        studio=StudioType.MERCHANDISE_STUDIO,
        description="Movement velocity classifier identifying fast movers, slow items, and dead stock.",
        dimensions=["item_code", "category", "brand", "velocity_tier", "days_since_last_sale"],
        measures=["MTR_STOCK_ON_HAND_QTY", "MTR_UNITS_SOLD", "MTR_SELL_THROUGH_PCT"],
        allowed_roles=["STORE_MANAGER", "MERCHANDISER", "ADMIN", "CEO"],
        drill_route="/inventory/aging",
        shoper_aliases=["473", "SR203900"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),

    # =========================================================================
    # 3. INVENTORY & VALUATION STUDIO
    # =========================================================================
    "RPT-INV-001": ReportRegistryEntry(
        report_id="RPT-INV-001",
        name="Stock Ledger & Valuation",
        studio=StudioType.INVENTORY_STUDIO,
        description="Opening balance + Inward - Outward +/- Adjustments = Closing Stock with landed cost valuation.",
        dimensions=["branch_id", "item_code", "barcode", "category", "brand", "batch_no"],
        measures=["MTR_STOCK_ON_HAND_QTY", "MTR_STOCK_VALUATION_AMT"],
        allowed_roles=["STORE_MANAGER", "WAREHOUSE_LEAD", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/inventory/stock-ledger-detail",
        shoper_aliases=["300", "350", "430", "450"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-INV-002": ReportRegistryEntry(
        report_id="RPT-INV-002",
        name="Stock Aging Analysis",
        studio=StudioType.INVENTORY_STUDIO,
        description="Stock partitioned into 0-30, 31-60, 61-90, and 90+ days aging buckets.",
        dimensions=["branch_id", "item_code", "category", "brand", "aging_bucket"],
        measures=["MTR_STOCK_ON_HAND_QTY", "MTR_STOCK_VALUATION_AMT"],
        allowed_roles=["STORE_MANAGER", "WAREHOUSE_LEAD", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/inventory/aging-detail",
        shoper_aliases=["472", "SR203800"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-INV-004": ReportRegistryEntry(
        report_id="RPT-INV-004",
        name="Physical Stock Take Discrepancy",
        studio=StudioType.INVENTORY_STUDIO,
        description="Physical stock count vs system balance variance reporting shrinkage and excess quantities.",
        dimensions=["audit_id", "branch_id", "item_code", "barcode", "variance_type"],
        measures=["MTR_STOCK_ON_HAND_QTY"],
        allowed_roles=["STORE_MANAGER", "WAREHOUSE_LEAD", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/inventory/stock-take",
        shoper_aliases=["380"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-INV-005": ReportRegistryEntry(
        report_id="RPT-INV-005",
        name="Inter-Branch In-Transit Register",
        studio=StudioType.INVENTORY_STUDIO,
        description="Multi-branch stock transfer register tracking dispatch notes, in-transit quantities, and receiving confirmations.",
        dimensions=["transfer_id", "source_branch", "target_branch", "transfer_date", "status"],
        measures=["MTR_UNITS_SOLD"],
        allowed_roles=["STORE_MANAGER", "WAREHOUSE_LEAD", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/inventory/transfers",
        shoper_aliases=["427", "SR231900"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),

    # =========================================================================
    # 4. TAX & FINANCIAL AUDIT STUDIO
    # =========================================================================
    "RPT-TAX-001": ReportRegistryEntry(
        report_id="RPT-TAX-001",
        name="Tax Register (GSTR-1 Matrix)",
        studio=StudioType.TAX_STUDIO,
        description="Statutory GSTR-1 compliant tax matrix: B2B, B2CL, B2CS, CDNR, and HSN summary (Taxable, CGST, SGST, IGST).",
        dimensions=["branch_id", "gst_rate", "tax_type", "hsn_code", "invoice_type"],
        measures=["MTR_TAXABLE_AMOUNT", "MTR_CGST_AMOUNT", "MTR_SGST_AMOUNT", "MTR_IGST_AMOUNT", "MTR_TAX_TOTAL"],
        allowed_roles=["ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/compliance/gst-detail",
        shoper_aliases=["414", "SR202300"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-TAX-004": ReportRegistryEntry(
        report_id="RPT-TAX-004",
        name="Cancelled & Voided Bills Audit",
        studio=StudioType.TAX_STUDIO,
        description="Immutable audit trail of cancelled invoices, cashier IDs, timestamps, and voiding reasons.",
        dimensions=["branch_id", "invoice_no", "cancelled_at", "cancelled_by", "reason_code"],
        measures=["MTR_GROSS_SALES", "MTR_TAX_TOTAL"],
        allowed_roles=["STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/audit/cancelled-invoices",
        shoper_aliases=["420", "SR210200"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-OPS-001": ReportRegistryEntry(
        report_id="RPT-OPS-001",
        name="Discount Given & Concession Audit",
        studio=StudioType.TAX_STUDIO,
        description="Line discount and invoice concession audit tracking discount percentage leakages against authorization thresholds.",
        dimensions=["branch_id", "invoice_no", "salesperson_id", "authorized_by", "discount_reason"],
        measures=["MTR_GROSS_SALES", "MTR_LINE_DISCOUNT", "MTR_HEADER_CONCESSION"],
        allowed_roles=["STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/sales/discount-audit",
        shoper_aliases=["416", "SR202100", "SR238400"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-MRC-003": ReportRegistryEntry(
        report_id="RPT-MRC-003",
        name="Item-wise Sales Returns Log",
        studio=StudioType.TAX_STUDIO,
        description="Item-wise sales returns log linked to original invoice numbers, refund payment modes, and return reasons.",
        dimensions=["branch_id", "credit_note_no", "original_invoice_no", "item_code", "return_reason"],
        measures=["MTR_UNITS_SOLD", "MTR_SALES_RETURNS"],
        allowed_roles=["STORE_MANAGER", "ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/sales/credit-notes",
        shoper_aliases=["425", "SR214100"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-FIN-001": ReportRegistryEntry(
        report_id="RPT-FIN-001",
        name="Customer Outstanding & Credit Aging",
        studio=StudioType.TAX_STUDIO,
        description="Credit customer ledger balances, payment terms, and 30/60/90 days overdue aging.",
        dimensions=["customer_id", "customer_name", "credit_tier", "aging_bucket"],
        measures=["MTR_NET_SALES"],
        allowed_roles=["ACCOUNTANT", "ADMIN", "CEO"],
        drill_route="/crm/customer-ledger",
        shoper_aliases=["613", "650"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),

    # =========================================================================
    # 5. EXECUTIVE MIS & INSIGHTS
    # =========================================================================
    "RPT-MIS-001": ReportRegistryEntry(
        report_id="RPT-MIS-001",
        name="Store-vs-Store Comparison Matrix",
        studio=StudioType.MIS_STUDIO,
        description="Multi-branch comparative matrix analyzing revenue, ticket counts, ABV, UPT, and margin contribution.",
        dimensions=["branch_id", "branch_name", "city", "store_format"],
        measures=["MTR_NET_SALES", "MTR_INVOICE_COUNT", "MTR_ABV", "MTR_UPT", "MTR_GROSS_MARGIN_PCT"],
        allowed_roles=["ADMIN", "CEO"],
        drill_route="/mis/store-comparison",
        shoper_aliases=["471", "SR203700"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-MIS-002": ReportRegistryEntry(
        report_id="RPT-MIS-002",
        name="Period-over-Period Growth (MoM / YoY)",
        studio=StudioType.MIS_STUDIO,
        description="Month-on-Month and Year-on-Year like-for-like sales growth, volume changes, and gross profit variances.",
        dimensions=["comparison_period", "branch_id", "category"],
        measures=["MTR_NET_SALES", "MTR_INVOICE_COUNT", "MTR_GROSS_MARGIN_AMT"],
        allowed_roles=["ADMIN", "CEO"],
        drill_route="/mis/growth-trends",
        shoper_aliases=["471"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-MIS-003": ReportRegistryEntry(
        report_id="RPT-MIS-003",
        name="Retail Basket Analytics",
        studio=StudioType.MIS_STUDIO,
        description="Customer basket analysis evaluating Average Basket Value (ABV), Units Per Transaction (UPT), and walk-in conversion.",
        dimensions=["branch_id", "time_slot", "day_of_week", "customer_tier"],
        measures=["MTR_INVOICE_COUNT", "MTR_UNITS_SOLD", "MTR_ABV", "MTR_UPT"],
        allowed_roles=["STORE_MANAGER", "ADMIN", "CEO"],
        drill_route="/mis/basket-analytics",
        shoper_aliases=["476", "SR222800"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
    "RPT-PRF-001": ReportRegistryEntry(
        report_id="RPT-PRF-001",
        name="Gross Margin & Net Contribution",
        studio=StudioType.MIS_STUDIO,
        description="Commercial profitability breakdown: Net Sales - Landed COGS = Gross Profit and Category Net Contribution.",
        dimensions=["branch_id", "department", "category", "brand"],
        measures=["MTR_NET_SALES", "MTR_COGS", "MTR_GROSS_MARGIN_AMT", "MTR_GROSS_MARGIN_PCT", "MTR_GMROI"],
        allowed_roles=["ADMIN", "CEO"],
        drill_route="/profitability/ledger",
        shoper_aliases=["SR229700"],
        contract_version="v1.0",
        metric_version="v1.0",
        schema_version="v1.0",
        security_policy_version="v1.0",
        status=ReportContractStatus.ACTIVE,
    ),
}
