"""baseline_schema

Revision ID: 12b68ccebec7
Revises: 
Create Date: 2026-07-11 18:13:42.356983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b68ccebec7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_groups', sa.Column('uuid', sa.String(length=36), nullable=False, server_default=sa.text("uuid_generate_v4()::varchar")))
    op.add_column('customer_groups', sa.Column('company_id', sa.String(length=50), nullable=True))
    op.add_column('customer_groups', sa.Column('branch_id', sa.String(length=50), nullable=True))
    op.add_column('customer_groups', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('customer_groups', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('customer_groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('customer_groups', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('customer_groups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer_groups', sa.Column('deleted_by', sa.String(length=100), nullable=True))
    op.add_column('customer_groups', sa.Column('version', sa.Integer(), nullable=True))
    op.alter_column('customer_groups', 'allowed_payment_methods',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.create_unique_constraint('customer_groups_uuid_key', 'customer_groups', ['uuid'])
    op.add_column('customers', sa.Column('uuid', sa.String(length=36), nullable=False, server_default=sa.text("uuid_generate_v4()::varchar")))
    op.add_column('customers', sa.Column('company_id', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('branch_id', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('customers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('deleted_by', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('version', sa.Integer(), nullable=True))
    op.alter_column('customers', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_customers_group'), table_name='customers')
    op.drop_index(op.f('idx_customers_mobile'), table_name='customers')
    op.create_index(op.f('ix_customers_customer_group_id'), 'customers', ['customer_group_id'], unique=False)
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_unique_constraint('customers_uuid_key', 'customers', ['uuid'])
    op.add_column('products', sa.Column('uuid', sa.String(length=36), nullable=False, server_default=sa.text("uuid_generate_v4()::varchar")))
    op.add_column('products', sa.Column('company_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('branch_id', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_by', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('version', sa.Integer(), nullable=True))
    op.alter_column('products', 'secondary_barcodes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_products_barcode'), table_name='products')
    op.drop_index(op.f('idx_products_category'), table_name='products')
    op.drop_constraint(op.f('products_barcode_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_unique_constraint('products_uuid_key', 'products', ['uuid'])
    op.alter_column('sales_invoice_items', 'invoice_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('idx_sales_invoice_item_invoice'), table_name='sales_invoice_items')
    op.create_index(op.f('ix_sales_invoice_items_invoice_id'), 'sales_invoice_items', ['invoice_id'], unique=False)
    op.add_column('sales_invoices', sa.Column('uuid', sa.String(length=36), nullable=False, server_default=sa.text("uuid_generate_v4()::varchar")))
    op.add_column('sales_invoices', sa.Column('company_id', sa.String(length=50), nullable=True))
    op.add_column('sales_invoices', sa.Column('branch_id', sa.String(length=50), nullable=True))
    op.add_column('sales_invoices', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('sales_invoices', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.add_column('sales_invoices', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('sales_invoices', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('sales_invoices', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sales_invoices', sa.Column('deleted_by', sa.String(length=100), nullable=True))
    op.add_column('sales_invoices', sa.Column('version', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_sales_invoice_customer'), table_name='sales_invoices')
    op.create_index(op.f('ix_sales_invoices_customer_id'), 'sales_invoices', ['customer_id'], unique=False)
    op.create_unique_constraint('sales_invoices_uuid_key', 'sales_invoices', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_invoices_uuid_key', 'sales_invoices', type_='unique')
    op.drop_index(op.f('ix_sales_invoices_customer_id'), table_name='sales_invoices')
    op.create_index(op.f('idx_sales_invoice_customer'), 'sales_invoices', ['customer_id'], unique=False)
    op.drop_column('sales_invoices', 'version')
    op.drop_column('sales_invoices', 'deleted_by')
    op.drop_column('sales_invoices', 'deleted_at')
    op.drop_column('sales_invoices', 'is_deleted')
    op.drop_column('sales_invoices', 'is_active')
    op.drop_column('sales_invoices', 'updated_by')
    op.drop_column('sales_invoices', 'created_by')
    op.drop_column('sales_invoices', 'branch_id')
    op.drop_column('sales_invoices', 'company_id')
    op.drop_column('sales_invoices', 'uuid')
    op.drop_index(op.f('ix_sales_invoice_items_invoice_id'), table_name='sales_invoice_items')
    op.create_index(op.f('idx_sales_invoice_item_invoice'), 'sales_invoice_items', ['invoice_id'], unique=False)
    op.alter_column('sales_invoice_items', 'invoice_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('products_uuid_key', 'products', type_='unique')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('idx_products_barcode'), 'products', ['barcode'], unique=False)
    op.alter_column('products', 'secondary_barcodes',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_column('products', 'version')
    op.drop_column('products', 'deleted_by')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'updated_by')
    op.drop_column('products', 'created_by')
    op.drop_column('products', 'branch_id')
    op.drop_column('products', 'company_id')
    op.drop_column('products', 'uuid')
    op.drop_constraint('customers_uuid_key', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_group_id'), table_name='customers')
    op.create_index(op.f('idx_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_index(op.f('idx_customers_group'), 'customers', ['customer_group_id'], unique=False)
    op.alter_column('customers', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_column('customers', 'version')
    op.drop_column('customers', 'deleted_by')
    op.drop_column('customers', 'deleted_at')
    op.drop_column('customers', 'is_deleted')
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'updated_by')
    op.drop_column('customers', 'created_by')
    op.drop_column('customers', 'branch_id')
    op.drop_column('customers', 'company_id')
    op.drop_column('customers', 'uuid')
    op.drop_constraint('customer_groups_uuid_key', 'customer_groups', type_='unique')
    op.alter_column('customer_groups', 'allowed_payment_methods',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_column('customer_groups', 'version')
    op.drop_column('customer_groups', 'deleted_by')
    op.drop_column('customer_groups', 'deleted_at')
    op.drop_column('customer_groups', 'is_deleted')
    op.drop_column('customer_groups', 'is_active')
    op.drop_column('customer_groups', 'updated_by')
    op.drop_column('customer_groups', 'created_by')
    op.drop_column('customer_groups', 'branch_id')
    op.drop_column('customer_groups', 'company_id')
    op.drop_column('customer_groups', 'uuid')
    # ### end Alembic commands ###
