"""
Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Designation  : Chief Systems Architect & Creator
Email        : support@smritibooks.com
Websites     : smritisys.com | smritibooks.com | erpnbook.com | aitdl.com
Version      : 3.18.0
Created      : 2026-07-14
Modified     : 2026-07-14
Copyright    : © SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software
Classification: Internal
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a24b31e30db'
down_revision: Union[str, Sequence[str], None] = '96b45b17b8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_jurisdiction_configs',
    sa.Column('company_state', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sales_orders',
    sa.Column('order_no', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_quotation_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sales_quotations',
    sa.Column('quotation_no', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sales_order_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_no'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('purchase_reorder_configs',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reorder_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('preferred_supplier_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('hsn_code', sa.String(length=15), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_items_order_id'), 'sales_order_items', ['order_id'], unique=False)
    op.create_table('sales_quotation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quotation_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('hsn_code', sa.String(length=15), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quotation_id'], ['sales_quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_quotation_items_quotation_id'), 'sales_quotation_items', ['quotation_id'], unique=False)
    op.create_table('sales_returns',
    sa.Column('return_no', sa.String(length=100), nullable=False),
    sa.Column('original_invoice_id', sa.String(length=50), nullable=False),
    sa.Column('credit_note_number', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_interstate', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['sales_invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_no'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_sales_returns_original_invoice_id'), 'sales_returns', ['original_invoice_id'], unique=False)
    op.create_table('sales_return_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_return_items_return_id'), 'sales_return_items', ['return_id'], unique=False)
    op.drop_column('customers', 'aadhaar')
    op.drop_column('customers', 'credit_days_override')
    op.drop_column('customers', 'billing_address_line2')
    op.drop_column('customers', 'blacklisted')
    op.drop_column('customers', 'alternate_mobile')
    op.drop_column('customers', 'billing_pincode')
    op.drop_column('customers', 'shipping_pincode')
    op.drop_column('customers', 'shipping_country')
    op.drop_column('customers', 'customer_type')
    op.drop_column('customers', 'occupation')
    op.drop_column('customers', 'shipping_same_as_billing')
    op.drop_column('customers', 'shipping_address_line2')
    op.drop_column('customers', 'shipping_address_line1')
    op.drop_column('customers', 'billing_state')
    op.drop_column('customers', 'route')
    op.drop_column('customers', 'credit_limit_override')
    op.drop_column('customers', 'salesperson')
    op.drop_column('customers', 'gender')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'shipping_state')
    op.drop_column('customers', 'price_list_id')
    op.drop_column('customers', 'shipping_city')
    op.drop_column('customers', 'billing_address_line1')
    op.drop_column('customers', 'pan')
    op.drop_column('customers', 'opening_balance')
    op.drop_column('customers', 'billing_city')
    op.drop_column('customers', 'opening_balance_type')
    op.drop_column('customers', 'date_of_birth')
    op.drop_column('customers', 'photo_url')
    op.drop_column('customers', 'territory')
    op.drop_column('customers', 'preferred_language')
    op.drop_column('customers', 'anniversary_date')
    op.drop_column('customers', 'lead_source')
    op.drop_column('customers', 'loyalty_member')
    op.drop_column('customers', 'billing_country')
    op.drop_index('ix_master_values_data_gin', table_name='master_values', postgresql_using='gin')
    op.drop_index('ix_master_values_master_type_id_active', table_name='master_values', postgresql_where='(active = true)')
    op.drop_constraint('master_values_master_type_id_code_key', 'master_values', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('master_values_master_type_id_code_key', 'master_values', ['master_type_id', 'code'])
    op.create_index('ix_master_values_master_type_id_active', 'master_values', ['master_type_id'], unique=False, postgresql_where='(active = true)')
    op.create_index('ix_master_values_data_gin', 'master_values', ['data'], unique=False, postgresql_using='gin')
    op.add_column('customers', sa.Column('billing_country', sa.VARCHAR(length=100), server_default=sa.text("'India'::character varying"), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('loyalty_member', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('lead_source', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('anniversary_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('preferred_language', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('territory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('opening_balance_type', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('billing_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('opening_balance', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('pan', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('billing_address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shipping_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('price_list_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shipping_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('salesperson', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('credit_limit_override', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('route', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('billing_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shipping_address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shipping_address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shipping_same_as_billing', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('customer_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shipping_country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('shipping_pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('billing_pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('alternate_mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('blacklisted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('billing_address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('credit_days_override', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('aadhaar', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sales_return_items_return_id'), table_name='sales_return_items')
    op.drop_table('sales_return_items')
    op.drop_index(op.f('ix_sales_returns_original_invoice_id'), table_name='sales_returns')
    op.drop_table('sales_returns')
    op.drop_index(op.f('ix_sales_quotation_items_quotation_id'), table_name='sales_quotation_items')
    op.drop_table('sales_quotation_items')
    op.drop_index(op.f('ix_sales_order_items_order_id'), table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_table('purchase_reorder_configs')
    op.drop_table('sales_quotations')
    op.drop_table('sales_orders')
    op.drop_table('purchase_jurisdiction_configs')
    # ### end Alembic commands ###
