"""
Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Email        : support@smritibooks.com
Websites     : smritisys.com | smritibooks.com | erpnbook.com | aitdl.com
Version      : 3.16.0
Created      : 2026-07-12
Modified     : 2026-07-12
Copyright    : © SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software
Classification: Internal

Revision ID: 6682e5e145bd
Revises: 94d408c3ba68
Create Date: 2026-07-12 16:03:54.995575
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6682e5e145bd'
down_revision: Union[str, Sequence[str], None] = '94d408c3ba68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_audit_logs',
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_compliance_audit_logs_service_id'), 'compliance_audit_logs', ['service_id'], unique=False)
    op.create_table('compliance_outboxes',
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_compliance_outboxes_idempotency_key'), 'compliance_outboxes', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_compliance_outboxes_service_id'), 'compliance_outboxes', ['service_id'], unique=False)
    op.create_table('government_services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('api_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environments', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('compliance_credentials',
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('encrypted_username', sa.Text(), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('encrypted_client_secret', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['government_services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_compliance_credentials_service_id'), 'compliance_credentials', ['service_id'], unique=False)
    op.alter_column('shifts', 'register_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('shifts', 'cashier_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint('shifts_profile_id_fkey', 'shifts', type_='foreignkey')
    op.drop_column('shifts', 'opening_cash')
    op.drop_column('shifts', 'sales_count')
    op.drop_column('shifts', 'start_time')
    op.drop_column('shifts', 'cashier')
    op.drop_column('shifts', 'sales_value')
    op.drop_column('shifts', 'warehouse')
    op.drop_column('shifts', 'end_time')
    op.drop_column('shifts', 'branch')
    op.drop_column('shifts', 'profile_id')
    op.drop_column('shifts', 'closing_cash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('closing_cash', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('profile_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('branch', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('warehouse', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('sales_value', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('cashier', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('sales_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('shifts', sa.Column('opening_cash', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True))
    op.create_foreign_key('shifts_profile_id_fkey', 'shifts', 'pos_profiles', ['profile_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('shifts', 'cashier_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('shifts', 'register_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_compliance_credentials_service_id'), table_name='compliance_credentials')
    op.drop_table('compliance_credentials')
    op.drop_table('government_services')
    op.drop_index(op.f('ix_compliance_outboxes_service_id'), table_name='compliance_outboxes')
    op.drop_index(op.f('ix_compliance_outboxes_idempotency_key'), table_name='compliance_outboxes')
    op.drop_table('compliance_outboxes')
    op.drop_index(op.f('ix_compliance_audit_logs_service_id'), table_name='compliance_audit_logs')
    op.drop_table('compliance_audit_logs')
    # ### end Alembic commands ###
