"""add_place_of_supply_server_default

Revision ID: 89221f5f1969
Revises: 0ee2915175be
Create Date: 2026-07-21 07:12:23.577762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89221f5f1969'
down_revision: Union[str, Sequence[str], None] = '0ee2915175be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_invoice_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_invoice_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_invoice_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_invoices', 'place_of_supply',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('sales_order_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_order_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_order_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_quotation_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_quotation_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_quotation_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_return_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_return_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sales_return_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_return_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_return_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_return_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_quotation_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_quotation_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_quotation_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_order_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_order_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_order_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_invoices', 'place_of_supply',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('sales_invoice_items', 'branch_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_invoice_items', 'company_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_invoice_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
