"""add_smriti_security_framework_tables

Revision ID: 8c4309461afc
Revises: f2a3b4c5d6e7
Create Date: 2026-07-18 14:05:25.858874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c4309461afc'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('barcode_providers', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('barcode_providers', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('barcode_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('barcode_providers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('barcode_providers', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index('ix_barcode_providers_company_branch', table_name='barcode_providers')
    op.drop_index('ix_barcode_providers_pool_code', table_name='barcode_providers')
    op.create_foreign_key(None, 'barcode_providers', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'barcode_providers', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('identity_rules', 'scope',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('identity_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('identity_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('identity_rules', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('identity_rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint('identity_rules_code_key', 'identity_rules', type_='unique')
    op.drop_index('ix_identity_rules_company_branch', table_name='identity_rules')
    op.drop_index('ix_identity_rules_code', table_name='identity_rules')
    op.create_index(op.f('ix_identity_rules_code'), 'identity_rules', ['code'], unique=True)
    op.create_foreign_key(None, 'identity_rules', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'identity_rules', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('product_identities', 'identity_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('product_identities', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('product_identities', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('product_identities', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_foreign_key(None, 'product_identities', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'product_identities', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('user_branch_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('user_branch_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_branch_assignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('user_company_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('user_company_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_company_assignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_foreign_key(None, 'user_company_assignments', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('user_store_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('user_store_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('user_store_assignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_store_assignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_store_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_store_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'user_company_assignments', type_='foreignkey')
    op.alter_column('user_company_assignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_company_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_company_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_branch_assignments', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('user_branch_assignments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_branch_assignments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'product_identities', type_='foreignkey')
    op.drop_constraint(None, 'product_identities', type_='foreignkey')
    op.alter_column('product_identities', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('product_identities', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product_identities', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('product_identities', 'identity_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'identity_rules', type_='foreignkey')
    op.drop_constraint(None, 'identity_rules', type_='foreignkey')
    op.drop_index(op.f('ix_identity_rules_code'), table_name='identity_rules')
    op.create_index('ix_identity_rules_code', 'identity_rules', ['code'], unique=False)
    op.create_index('ix_identity_rules_company_branch', 'identity_rules', ['company_id', 'branch_id'], unique=False)
    op.create_unique_constraint('identity_rules_code_key', 'identity_rules', ['code'])
    op.alter_column('identity_rules', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('identity_rules', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('identity_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('identity_rules', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('identity_rules', 'scope',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'barcode_providers', type_='foreignkey')
    op.drop_constraint(None, 'barcode_providers', type_='foreignkey')
    op.create_index('ix_barcode_providers_pool_code', 'barcode_providers', ['pool_code'], unique=False)
    op.create_index('ix_barcode_providers_company_branch', 'barcode_providers', ['company_id', 'branch_id'], unique=False)
    op.alter_column('barcode_providers', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('barcode_providers', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('barcode_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('barcode_providers', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('barcode_providers', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    # ### end Alembic commands ###
