"""add_companies_and_branches

Revision ID: 931451e6eea2
Revises: 12b68ccebec7
Create Date: 2026-07-11 19:02:20.459186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '931451e6eea2'
down_revision: Union[str, Sequence[str], None] = '12b68ccebec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('branches',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_branches_company_id'), 'branches', ['company_id'], unique=False)
    op.create_foreign_key('fk_customer_groups_company_id', 'customer_groups', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_customer_groups_branch_id', 'customer_groups', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_customers_branch_id', 'customers', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_customers_company_id', 'customers', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_products_company_id', 'products', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_products_branch_id', 'products', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_sales_invoices_branch_id', 'sales_invoices', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_sales_invoices_company_id', 'sales_invoices', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sales_invoices_company_id_fkey', 'sales_invoices', type_='foreignkey')
    op.drop_constraint('sales_invoices_branch_id_fkey', 'sales_invoices', type_='foreignkey')
    op.drop_constraint('products_branch_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_company_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('customers_company_id_fkey', 'customers', type_='foreignkey')
    op.drop_constraint('customers_branch_id_fkey', 'customers', type_='foreignkey')
    op.drop_constraint('customer_groups_branch_id_fkey', 'customer_groups', type_='foreignkey')
    op.drop_constraint('customer_groups_company_id_fkey', 'customer_groups', type_='foreignkey')
    op.drop_index(op.f('ix_branches_company_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_table('companies')
    # ### end Alembic commands ###
