"""add stock movements table

Revision ID: 94d408c3ba68
Revises: d1e2bb4fa3a2
Create Date: 2026-07-12 07:41:43.094655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d408c3ba68'
down_revision: Union[str, Sequence[str], None] = '9862a004de1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('reference_doc_type', sa.String(length=50), nullable=True),
    sa.Column('reference_doc_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('bin', sa.String(length=50), nullable=True),
    sa.Column('batch', sa.String(length=50), nullable=True),
    sa.Column('serial', sa.String(length=50), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('source_module', sa.String(length=50), nullable=True),
    sa.Column('approval', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    # ### end Alembic commands ###
