"""add_cashier_warehouse_is_locked_to_cash_registers

Revision ID: 94fdee7fd6ab
Revises: h4i5j6k7l8m9
Create Date: 2026-07-16 06:14:53.034655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fdee7fd6ab'
down_revision: Union[str, Sequence[str], None] = 'h4i5j6k7l8m9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_registers', sa.Column('cashier', sa.String(length=100), nullable=True))
    op.add_column('cash_registers', sa.Column('warehouse', sa.String(length=100), nullable=True))
    op.add_column('cash_registers', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.alter_column('sales_returns', 'credit_note_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_returns', 'credit_note_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('cash_registers', 'is_locked')
    op.drop_column('cash_registers', 'warehouse')
    op.drop_column('cash_registers', 'cashier')
    # ### end Alembic commands ###
