"""
Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Email        : support@smritibooks.com
Websites     : smritibooks.com | erpnbook.com | aitdl.com
Version      : 3.14.4
Created      : 2026-07-11
Modified     : 2026-07-11
Copyright    : © SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software

add_pos_shift_tables

Revision ID: cc8a527deb42
Revises: 59cbc26b919c
Create Date: 2026-07-11 20:09:07.734491
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8a527deb42'
down_revision: Union[str, Sequence[str], None] = '59cbc26b919c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ── cash_registers + shifts: created idempotently (may already exist) ─────
    op.execute("""
        CREATE TABLE IF NOT EXISTS cash_registers (
            name        VARCHAR(100) NOT NULL,
            code        VARCHAR(50)  NOT NULL,
            notes       TEXT,
            id          VARCHAR(50)  NOT NULL PRIMARY KEY,
            uuid        VARCHAR(36)  NOT NULL UNIQUE DEFAULT uuid_generate_v4()::varchar,
            company_id  VARCHAR(50)  REFERENCES companies(id) ON DELETE RESTRICT,
            branch_id   VARCHAR(50)  REFERENCES branches(id)  ON DELETE RESTRICT,
            created_at  TIMESTAMPTZ,
            modified_at TIMESTAMPTZ,
            created_by  VARCHAR(100),
            updated_by  VARCHAR(100),
            is_active   BOOLEAN DEFAULT TRUE,
            is_deleted  BOOLEAN DEFAULT FALSE,
            deleted_at  TIMESTAMPTZ,
            deleted_by  VARCHAR(100),
            version     INTEGER DEFAULT 1
        )
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS shifts (
            register_id      VARCHAR(50) REFERENCES cash_registers(id) ON DELETE RESTRICT,
            cashier_id       VARCHAR(50) REFERENCES users(id) ON DELETE RESTRICT,
            profile_id       VARCHAR(50) REFERENCES pos_profiles(id) ON DELETE RESTRICT,
            status           VARCHAR(20) NOT NULL DEFAULT 'OPEN',
            opened_at        TIMESTAMPTZ NOT NULL,
            closed_at        TIMESTAMPTZ,
            opening_balance  NUMERIC(15,2) NOT NULL DEFAULT 0.00,
            cash_sales_total NUMERIC(15,2) NOT NULL DEFAULT 0.00,
            card_sales_total NUMERIC(15,2) NOT NULL DEFAULT 0.00,
            upi_sales_total  NUMERIC(15,2) NOT NULL DEFAULT 0.00,
            total_sales      NUMERIC(15,2) NOT NULL DEFAULT 0.00,
            total_invoices   VARCHAR(10)   NOT NULL DEFAULT '0',
            closing_balance  NUMERIC(15,2),
            expected_cash    NUMERIC(15,2),
            variance         NUMERIC(15,2),
            closing_notes    TEXT,
            id          VARCHAR(50)  NOT NULL PRIMARY KEY,
            uuid        VARCHAR(36)  NOT NULL UNIQUE DEFAULT uuid_generate_v4()::varchar,
            company_id  VARCHAR(50)  REFERENCES companies(id) ON DELETE RESTRICT,
            branch_id   VARCHAR(50)  REFERENCES branches(id)  ON DELETE RESTRICT,
            created_at  TIMESTAMPTZ,
            modified_at TIMESTAMPTZ,
            created_by  VARCHAR(100),
            updated_by  VARCHAR(100),
            is_active   BOOLEAN DEFAULT TRUE,
            is_deleted  BOOLEAN DEFAULT FALSE,
            deleted_at  TIMESTAMPTZ,
            deleted_by  VARCHAR(100),
            version     INTEGER DEFAULT 1,
            
            -- Node API Compatibility Columns
            cashier      VARCHAR(255),
            warehouse    VARCHAR(255),
            branch       VARCHAR(255),
            start_time   TIMESTAMPTZ,
            end_time     TIMESTAMPTZ,
            opening_cash NUMERIC(15,2) DEFAULT 0.00,
            closing_cash NUMERIC(15,2),
            sales_count  INT DEFAULT 0,
            sales_value  NUMERIC(15,2) DEFAULT 0.00
        )
    """)

    # ── sales_invoices: add shift_id + payment_mode (idempotent) ─────────────
    op.execute("""
        ALTER TABLE sales_invoices
            ADD COLUMN IF NOT EXISTS shift_id    VARCHAR(50) REFERENCES shifts(id) ON DELETE SET NULL,
            ADD COLUMN IF NOT EXISTS payment_mode VARCHAR(20) DEFAULT 'CASH'
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_sales_invoices_shift_id ON sales_invoices(shift_id)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_sales_invoices_shift_id'), table_name='sales_invoices')
    op.drop_column('sales_invoices', 'payment_mode')
    op.drop_column('sales_invoices', 'shift_id')
    # ### end Alembic commands ###
