"""Rescript Product.code and Product.sku uniqueness to UNIQUE(company_id, code/sku)

Revision ID: v1502_tenant_scoped_product_code_sku
Revises: v1501_barcode_sourcing_multi_mode
Create Date: 2026-08-09 04:40:00.000000

Rationale
---------
Product.code (SKU code) is merchant-owned catalog identity.  Two different
tenants (company_id) may legitimately use the same code string for entirely
different SKUs.  The previous global UNIQUE(code) / UNIQUE(sku) constraints
were incorrect for a multi-tenant platform and prevented cross-tenant
onboarding of merchants who share common product codes.

Barcode columns (Product.barcode, ProductBarcode.barcode) are NOT changed:
physical GS1 EAN-13 barcodes must remain globally unique to prevent POS
scan collisions across tenants.

Safety
------
A pre-flight SELECT verifies that NO duplicate (company_id, code) or
(company_id, sku) pairs exist before the old constraint is dropped.  The
migration raises an error if duplicates are found, requiring manual cleanup
before it can proceed.

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import ProgrammingError

# revision identifiers, used by Alembic.
revision = 'v1502_tenant_scoped_product_code_sku'
down_revision = 'v1501_barcode_sourcing_multi_mode'
branch_labels = None
depends_on = None


def _index_exists(conn, index_name: str) -> bool:
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM pg_indexes WHERE indexname = :name"
        ),
        {"name": index_name}
    )
    return result.scalar() is not None


def _constraint_exists(conn, table_name: str, constraint_name: str) -> bool:
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM information_schema.table_constraints "
            "WHERE table_name = :tbl AND constraint_name = :cname"
        ),
        {"tbl": table_name, "cname": constraint_name}
    )
    return result.scalar() is not None


def upgrade():
    conn = op.get_bind()

    # ── Pre-flight safety check: duplicate (company_id, code) ──────────────
    dup_code = conn.execute(
        sa.text(
            "SELECT company_id, code, COUNT(*) AS cnt "
            "FROM products "
            "WHERE is_deleted = FALSE "
            "GROUP BY company_id, code "
            "HAVING COUNT(*) > 1 "
            "LIMIT 1"
        )
    ).first()
    if dup_code:
        raise RuntimeError(
            f"Migration v1502 ABORTED: duplicate (company_id='{dup_code.company_id}', "
            f"code='{dup_code.code}') found in products table. "
            "Resolve duplicates before re-running this migration."
        )

    # ── Pre-flight safety check: duplicate (company_id, sku) ───────────────
    dup_sku = conn.execute(
        sa.text(
            "SELECT company_id, sku, COUNT(*) AS cnt "
            "FROM products "
            "WHERE is_deleted = FALSE AND sku IS NOT NULL AND sku <> '' "
            "GROUP BY company_id, sku "
            "HAVING COUNT(*) > 1 "
            "LIMIT 1"
        )
    ).first()
    if dup_sku:
        raise RuntimeError(
            f"Migration v1502 ABORTED: duplicate (company_id='{dup_sku.company_id}', "
            f"sku='{dup_sku.sku}') found in products table. "
            "Resolve duplicates before re-running this migration."
        )

    # ── Pre-flight safety check: NULL company_id ────────────────────────────
    null_company = conn.execute(
        sa.text(
            "SELECT COUNT(*) FROM products WHERE company_id IS NULL AND is_deleted = FALSE"
        )
    ).scalar()
    if null_company and null_company > 0:
        raise RuntimeError(
            f"Migration v1502 ABORTED: {null_company} product rows have NULL company_id. "
            "All products must be assigned a company before this constraint can be applied."
        )

    # ── Drop old global unique constraints on 'code' ─────────────────────────
    # The constraint name may be 'uq_products_code' or autogenerated by SQLAlchemy
    # We detect by index name.
    if _index_exists(conn, "ix_products_code") or _index_exists(conn, "products_code_key"):
        try:
            op.drop_constraint("products_code_key", "products", type_="unique")
        except Exception:
            pass

    # Drop the column-level unique index (SQLAlchemy auto-names it)
    try:
        conn.execute(sa.text(
            "ALTER TABLE products DROP CONSTRAINT IF EXISTS products_code_key"
        ))
    except Exception:
        pass

    # ── Drop old global unique constraint on 'sku' ──────────────────────────
    try:
        conn.execute(sa.text(
            "ALTER TABLE products DROP CONSTRAINT IF EXISTS products_sku_key"
        ))
    except Exception:
        pass

    # ── Create new UNIQUE(company_id, code) composite constraint ─────────────
    if not _constraint_exists(conn, "products", "uq_products_company_code"):
        op.create_unique_constraint(
            "uq_products_company_code",
            "products",
            ["company_id", "code"]
        )

    # ── Create new UNIQUE(company_id, sku) composite constraint ─────────────
    if not _constraint_exists(conn, "products", "uq_products_company_sku"):
        op.create_unique_constraint(
            "uq_products_company_sku",
            "products",
            ["company_id", "sku"]
        )


def downgrade():
    conn = op.get_bind()

    # Drop composite constraints
    try:
        conn.execute(sa.text(
            "ALTER TABLE products DROP CONSTRAINT IF EXISTS uq_products_company_code"
        ))
    except Exception:
        pass

    try:
        conn.execute(sa.text(
            "ALTER TABLE products DROP CONSTRAINT IF EXISTS uq_products_company_sku"
        ))
    except Exception:
        pass

    # Restore global unique constraints (only safe if no cross-tenant duplicates exist)
    if not _constraint_exists(conn, "products", "products_code_key"):
        op.create_unique_constraint("products_code_key", "products", ["code"])

    if not _constraint_exists(conn, "products", "products_sku_key"):
        op.create_unique_constraint("products_sku_key", "products", ["sku"])
