"""Refactor SKU, Barcode, and Item-Variant Architecture to Canonical Blueprint

Revision ID: v1518_sku_barcode_architecture_refactor
Revises: v1517_item_master_integrity_refactor, v1336_gift_cards_and_einvoice
Create Date: 2026-10-05

Project      : SMRITI Retail OS
Author       : Jawahar Ramkripal Mallah
Designation  : Chief Systems Architect & Creator
Email        : support@smritibooks.com
Websites     : smritibooks.com | erpnbook.com | aitdl.com
Version      : 3.16.0
Copyright    : (C) SMRITIBooks.com. All Rights Reserved.
License      : Proprietary Commercial Software
Classification: Internal

Architecture Invariants Enforced:
1. Technical Identity: item_variants.id (UUID string) is the technical PK.
2. Canonical Business Identity: item_variants.variant_sku (UNIQUE within company_id scope).
3. Barcode Registry: item_barcodes is a 1-to-many registry for item_variants.
4. Barcode Constraints:
   - Exactly ONE active primary barcode per variant (enforced via partial UNIQUE index).
   - Barcode uniqueness scoped to company (enforced via uq_barcodes_company_barcode).
5. Transaction Identity:
   - sales_invoice_items.variant_id backfilled from products.item_variant_id.
   - stock_movements.variant_id backfilled from products.item_variant_id.
   - purchase_order_items.variant_id backfilled from products.item_variant_id.
   - purchase_receipt_items.variant_id backfilled from products.item_variant_id.
   - Added sku_snapshot column to sales_invoice_items for historical readability.
"""

from alembic import op
import sqlalchemy as sa


revision = "v1518_sku_barcode_architecture_refactor"
down_revision = ("v1517_item_master_integrity_refactor", "v1336_gift_cards_and_einvoice")
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()

    # ─────────────────────────────────────────────────────────────
    # Step 1: Remediate Multiple Primary Barcodes per Variant
    # ─────────────────────────────────────────────────────────────
    # For variants with multiple barcodes marked is_primary=true:
    # Rank barcodes: Prefer EAN13 over CUSTOM, prefer non-synthetic (not ending in 'D'),
    # then earliest created_at. Retain rank 1 as primary, demote rank > 1 to additional.
    conn.execute(sa.text("""
        WITH ranked_primaries AS (
            SELECT id,
                   ROW_NUMBER() OVER (
                       PARTITION BY company_id, variant_id
                       ORDER BY
                           CASE WHEN barcode_type = 'EAN13' THEN 1 ELSE 2 END,
                           CASE WHEN barcode LIKE '%D' THEN 2 ELSE 1 END,
                           created_at ASC
                   ) AS rnk
            FROM item_barcodes
            WHERE is_deleted = false AND is_primary = true AND variant_id IS NOT NULL
        )
        UPDATE item_barcodes b
        SET is_primary = false,
            modified_at = NOW()
        FROM ranked_primaries rp
        WHERE b.id = rp.id AND rp.rnk > 1;
    """))

    # ─────────────────────────────────────────────────────────────
    # Step 1b: Deactivate Synthetic 'D' Barcodes (Gate 1 Compliance)
    # ─────────────────────────────────────────────────────────────
    # Historical synthetic barcodes generated by legacy sync (e.g. 8904551002945D)
    # must be deactivated so they do not participate in lookup, while preserving audit history.
    conn.execute(sa.text("""
        UPDATE item_barcodes
        SET is_active = false,
            is_primary = false,
            modified_at = NOW()
        WHERE is_deleted = false
          AND barcode IN (
              '8904551002945D',
              '8904551002952D',
              '8904551002969D',
              '8904551002976D',
              '8904551002983D',
              '8904551002990D',
              '8904551003003D',
              '8904551003010D',
              '890457170D'
          );
    """))

    # ─────────────────────────────────────────────────────────────
    # Step 2: Enforce Database Constraint: Exactly One Active Primary Barcode Per Variant
    # ─────────────────────────────────────────────────────────────
    # Drop old non-unique index if exists
    conn.execute(sa.text("""
        DROP INDEX IF EXISTS ix_item_barcodes_company_primary;
        DROP INDEX IF EXISTS uq_barcodes_one_primary_per_variant;
    """))

    # Create partial unique index
    conn.execute(sa.text("""
        CREATE UNIQUE INDEX uq_barcodes_one_primary_per_variant
        ON item_barcodes (company_id, variant_id)
        WHERE (is_primary = true AND is_deleted = false AND variant_id IS NOT NULL);
    """))

    # ─────────────────────────────────────────────────────────────
    # Step 3: Add sku_snapshot Column to sales_invoice_items
    # ─────────────────────────────────────────────────────────────
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'sales_invoice_items' AND column_name = 'sku_snapshot'
            ) THEN
                ALTER TABLE sales_invoice_items ADD COLUMN sku_snapshot VARCHAR(100);
                UPDATE sales_invoice_items SET sku_snapshot = code WHERE sku_snapshot IS NULL;
            END IF;
        END $$;
    """))

    # ─────────────────────────────────────────────────────────────
    # Step 4: Backfill Transactions with item_variant_id (variant_id)
    # ─────────────────────────────────────────────────────────────
    # 4a. sales_invoice_items: backfill variant_id from products.item_variant_id
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'sales_invoice_items' AND column_name = 'variant_id'
            ) THEN
                UPDATE sales_invoice_items sii
                SET variant_id = p.item_variant_id
                FROM products p
                WHERE sii.product_id = p.id
                  AND sii.variant_id IS NULL
                  AND p.item_variant_id IS NOT NULL;
            END IF;
        END $$;
    """))

    # 4b. stock_movements: backfill variant_id from products.item_variant_id
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'stock_movements' AND column_name = 'variant_id'
            ) THEN
                UPDATE stock_movements sm
                SET variant_id = p.item_variant_id
                FROM products p
                WHERE sm.product_id = p.id
                  AND sm.variant_id IS NULL
                  AND p.item_variant_id IS NOT NULL;
            END IF;
        END $$;
    """))

    # 4c. purchase_order_items: backfill variant_id from products.item_variant_id
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'purchase_order_items' AND column_name = 'variant_id'
            ) THEN
                UPDATE purchase_order_items poi
                SET variant_id = p.item_variant_id
                FROM products p
                WHERE poi.product_id = p.id
                  AND poi.variant_id IS NULL
                  AND p.item_variant_id IS NOT NULL;
            END IF;
        END $$;
    """))

    # 4d. purchase_receipt_items: backfill variant_id from products.item_variant_id
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'purchase_receipt_items' AND column_name = 'variant_id'
            ) THEN
                UPDATE purchase_receipt_items pri
                SET variant_id = p.item_variant_id
                FROM products p
                WHERE pri.product_id = p.id
                  AND pri.variant_id IS NULL
                  AND p.item_variant_id IS NOT NULL;
            END IF;
        END $$;
    """))

    # ─────────────────────────────────────────────────────────────
    # Step 5: Backfill item_id on stock_movements from item_variants where missing
    # ─────────────────────────────────────────────────────────────
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'stock_movements' AND column_name = 'item_id'
            ) AND EXISTS (
                SELECT 1 FROM information_schema.tables WHERE table_name = 'item_variants'
            ) THEN
                UPDATE stock_movements sm
                SET item_id = v.item_id
                FROM item_variants v
                WHERE sm.variant_id = v.id
                  AND sm.item_id IS NULL;
            END IF;
        END $$;
    """))


def downgrade() -> None:
    conn = op.get_bind()

    # Drop the partial unique index
    conn.execute(sa.text("""
        DROP INDEX IF EXISTS uq_barcodes_one_primary_per_variant;
    """))

    # Re-create standard index
    conn.execute(sa.text("""
        CREATE INDEX ix_item_barcodes_company_primary
        ON item_barcodes (company_id, variant_id)
        WHERE ((is_primary = true) AND (is_deleted = false));
    """))

    # Drop sku_snapshot column
    conn.execute(sa.text("""
        ALTER TABLE sales_invoice_items DROP COLUMN IF EXISTS sku_snapshot;
    """))
