/**
 * Project      : SMRITI Retail OS
 * System       : SMRITI Metadata Platform (SMP-M)
 * Component    : ApparelPack (Apparel, Garments & Footwear Industry Pack)
 * Author       : Jawahar Ramkripal Mallah
 * Designation  : Chief Systems Architect & Creator
 * Version      : 1.0.0
 * License      : Proprietary Commercial Software
 * Copyright    : © SMRITIBooks.com. All Rights Reserved.
 */

import { AttributeDefinition } from "../attributes/AttributeDefinition.js";

export const APPAREL_INDUSTRY_PACK: AttributeDefinition[] = [
  {
    attributeCode: "brand",
    internalName: "Brand",
    displayLabel: "Brand",
    description: "Apparel or Footwear Brand Name",
    businessDomain: "global",
    dataType: "text",
    controlType: "textbox",
    behavior: {
      visible: true,
      editable: true,
      mandatory: true,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 1,
    category: "General",
    ai: {
      aiDescription: "Manufacturer or Retail Brand Name",
      businessMeaning: "Product Brand Owner",
      synonyms: ["Brand", "Manufacturer", "Company", "OEM", "Maker"],
      confidence: 0.98,
    },
    version: 1,
    published: true,
  },
  {
    attributeCode: "color",
    internalName: "Color",
    displayLabel: "Color / Shade",
    description: "Garment or Footwear Color Variant",
    businessDomain: "global",
    dataType: "text",
    controlType: "colorpicker",
    behavior: {
      visible: true,
      editable: true,
      mandatory: false,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 2,
    category: "Variants",
    ai: {
      aiDescription: "Color or Shade Code",
      synonyms: ["Color", "Shade", "Hue", "Color Code"],
      confidence: 0.95,
    },
    version: 1,
    published: true,
  },
  {
    attributeCode: "size",
    internalName: "Size",
    displayLabel: "Size",
    description: "Garment or Footwear Size Code",
    businessDomain: "global",
    dataType: "text",
    controlType: "dropdown",
    options: [
      { label: "Size 6", value: "6" },
      { label: "Size 7", value: "7" },
      { label: "Size 8", value: "8" },
      { label: "Size 9", value: "9" },
      { label: "Size 10", value: "10" },
      { label: "S", value: "S" },
      { label: "M", value: "M" },
      { label: "L", value: "L" },
      { label: "XL", value: "XL" },
      { label: "XXL", value: "XXL" },
    ],
    behavior: {
      visible: true,
      editable: true,
      mandatory: true,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 3,
    category: "Variants",
    ai: {
      synonyms: ["Size", "Dimension", "Waist", "Length"],
      confidence: 0.96,
    },
    version: 1,
    published: true,
  },
  {
    attributeCode: "style",
    internalName: "Style",
    displayLabel: "Style / Art No.",
    description: "Article or Design Pattern Code",
    businessDomain: "global",
    dataType: "text",
    controlType: "textbox",
    behavior: {
      visible: true,
      editable: true,
      mandatory: false,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 4,
    category: "Design",
    version: 1,
    published: true,
  },
  {
    attributeCode: "fabric",
    internalName: "Fabric",
    displayLabel: "Fabric / Material",
    description: "Material composition (e.g. 100% Cotton, Denim, Leather)",
    businessDomain: "global",
    dataType: "text",
    controlType: "textbox",
    behavior: {
      visible: true,
      editable: true,
      mandatory: false,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: false,
      mobileVisible: false,
      aiVisible: true,
    },
    sequence: 5,
    category: "Material",
    version: 1,
    published: true,
  },
];
