/**
 * Project      : SMRITI Retail OS
 * System       : SMRITI Metadata Platform (SMP-M)
 * Component    : JewelleryPack (Jewellery, Precious Metals & Gemstones Pack)
 * Author       : Jawahar Ramkripal Mallah
 * Designation  : Chief Systems Architect & Creator
 * Version      : 1.0.0
 * License      : Proprietary Commercial Software
 * Copyright    : © SMRITIBooks.com. All Rights Reserved.
 */

import { AttributeDefinition } from "../attributes/AttributeDefinition.js";

export const JEWELLERY_INDUSTRY_PACK: AttributeDefinition[] = [
  {
    attributeCode: "metal",
    internalName: "Metal",
    displayLabel: "Metal Type",
    description: "Precious Metal Type (Gold, Silver, Platinum)",
    businessDomain: "global",
    dataType: "dropdown",
    controlType: "dropdown",
    options: [
      { label: "Gold", value: "Gold" },
      { label: "Silver", value: "Silver" },
      { label: "Platinum", value: "Platinum" },
    ],
    behavior: {
      visible: true,
      editable: true,
      mandatory: true,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 1,
    category: "Specifications",
    version: 1,
    published: true,
  },
  {
    attributeCode: "purity",
    internalName: "Purity",
    displayLabel: "Purity (Karat / %)",
    description: "Gold / Silver Purity Grade",
    businessDomain: "global",
    dataType: "dropdown",
    controlType: "dropdown",
    options: [
      { label: "24K (99.9%)", value: "24K" },
      { label: "22K (91.6% BIS Hallmark)", value: "22K" },
      { label: "18K (75.0%)", value: "18K" },
      { label: "14K (58.5%)", value: "14K" },
      { label: "925 Sterling Silver", value: "925 Silver" },
    ],
    behavior: {
      visible: true,
      editable: true,
      mandatory: true,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 2,
    category: "Specifications",
    version: 1,
    published: true,
  },
  {
    attributeCode: "weight",
    internalName: "Weight",
    displayLabel: "Gross Weight (gm)",
    description: "Item Weight in Grams",
    businessDomain: "global",
    dataType: "decimal",
    controlType: "textbox",
    precision: 3,
    behavior: {
      visible: true,
      editable: true,
      mandatory: true,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 3,
    category: "Weight & Stones",
    version: 1,
    published: true,
  },
  {
    attributeCode: "stone",
    internalName: "Stone",
    displayLabel: "Stone / Diamond Type",
    description: "Precious Stone details (e.g., Diamond VVS, Ruby)",
    businessDomain: "global",
    dataType: "text",
    controlType: "textbox",
    behavior: {
      visible: true,
      editable: true,
      mandatory: false,
      printable: true,
      searchable: true,
      filterable: true,
      sortable: true,
      barcodeVisible: true,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 4,
    category: "Weight & Stones",
    version: 1,
    published: true,
  },
  {
    attributeCode: "makingCharge",
    internalName: "MakingCharge",
    displayLabel: "Making Charge (₹/gm)",
    description: "Labor and craftsmanship charges per gram",
    businessDomain: "global",
    dataType: "currency",
    controlType: "textbox",
    behavior: {
      visible: true,
      editable: true,
      mandatory: false,
      printable: true,
      searchable: false,
      filterable: true,
      sortable: true,
      barcodeVisible: false,
      mobileVisible: true,
      aiVisible: true,
    },
    sequence: 5,
    category: "Pricing",
    version: 1,
    published: true,
  },
];
