/**
 * Project      : SMRITI Retail OS
 * Author       : Jawahar Ramkripal Mallah
 * Designation  : Chief Systems Architect & Creator
 * Email        : support@smritibooks.com
 * Websites     : smritibooks.com | erpnbook.com | aitdl.com
 * Version      : 3.122.0
 * Created      : 2026-08-28
 * Modified     : 2026-08-28
 * Copyright    : © SMRITIBooks.com. All Rights Reserved.
 * License      : Proprietary Commercial Software
 * Classification: Internal
 */

/**
 * Purchase Order Auto-Generation Engine
 *
 * Detects reorder-point breaches and auto-generates POs:
 *   Breach Detection : `detectBreaches()` — stock < reorderPoint → breach record
 *   PO Generation   : `generatePO()` — one PO per supplier from breach list
 *   Consolidation   : `consolidatePOs()` — merge multi-SKU breaches per supplier
 *   MOQ Enforcement : suggestedQty = max(reorderQty, supplierMOQ)
 *   Status flow     : DRAFT → SUBMITTED → ACKNOWLEDGED → CANCELLED
 */

export type AutoPOStatus  = "DRAFT" | "SUBMITTED" | "ACKNOWLEDGED" | "CANCELLED";
export type BreachSeverity = "CRITICAL" | "LOW" | "NORMAL";  // critical = stockOut

export interface StockItem {
  sku:          string;
  productName:  string;
  branchCode:   string;
  supplierId:   string;
  supplierName: string;
  currentStock: number;
  reorderPoint: number;
  reorderQty:   number;      // Preferred replenishment quantity
  supplierMOQ:  number;      // Minimum Order Quantity from supplier
  unitCost:     number;
  leadTimeDays: number;
}

export interface ReorderBreach {
  sku:           string;
  productName:   string;
  branchCode:    string;
  supplierId:    string;
  supplierName:  string;
  currentStock:  number;
  reorderPoint:  number;
  shortfall:     number;     // reorderPoint - currentStock
  suggestedQty:  number;     // max(reorderQty, supplierMOQ)
  unitCost:      number;
  lineTotal:     number;
  leadTimeDays:  number;
  severity:      BreachSeverity;
}

export interface AutoPOLine {
  lineId:       string;
  sku:          string;
  productName:  string;
  orderedQty:   number;
  unitCost:     number;
  lineTotal:    number;
  reorderPoint: number;
  currentStock: number;
}

export interface AutoPurchaseOrder {
  poId:          string;
  poNo:          string;
  supplierId:    string;
  supplierName:  string;
  branchCode:    string;
  status:        AutoPOStatus;
  lines:         AutoPOLine[];
  totalLines:    number;
  totalQty:      number;
  totalValue:    number;
  isAutoGenerated: boolean;
  generatedAt:   string;
  submittedAt?:  string;
  acknowledgedAt?: string;
  cancelledAt?:  string;
  cancelReason?: string;
  expectedDelivery?: string;
}

export class AutoPOEngine {
  private static counter     = 1;
  private static lineCounter = 1;

  /**
   * Detect all reorder-point breaches in the given stock list.
   * severity: CRITICAL = stock === 0 (stockout), LOW = stock ≤ reorderPoint/2, NORMAL otherwise
   */
  public static detectBreaches(items: StockItem[]): ReorderBreach[] {
    return items
      .filter((i) => i.currentStock <= i.reorderPoint)
      .map((i) => {
        const shortfall    = i.reorderPoint - i.currentStock;
        const suggestedQty = Math.max(i.reorderQty, i.supplierMOQ);
        const severity: BreachSeverity =
          i.currentStock === 0              ? "CRITICAL"
          : i.currentStock <= i.reorderPoint / 2 ? "LOW"
          : "NORMAL";
        return {
          sku:          i.sku,
          productName:  i.productName,
          branchCode:   i.branchCode,
          supplierId:   i.supplierId,
          supplierName: i.supplierName,
          currentStock: i.currentStock,
          reorderPoint: i.reorderPoint,
          shortfall,
          suggestedQty,
          unitCost:     i.unitCost,
          lineTotal:    Math.round(suggestedQty * i.unitCost * 100) / 100,
          leadTimeDays: i.leadTimeDays,
          severity,
        };
      })
      .sort((a, b) =>
        (a.severity === "CRITICAL" ? 0 : a.severity === "LOW" ? 1 : 2) -
        (b.severity === "CRITICAL" ? 0 : b.severity === "LOW" ? 1 : 2)
      );
  }

  /**
   * Generate a single PO for one supplier from their breach lines.
   * All lines for that supplier are consolidated into one PO.
   */
  public static generatePO(
    breaches:   ReorderBreach[],
    supplierId: string,
    branchCode: string
  ): AutoPurchaseOrder {
    const now          = new Date().toISOString();
    const supplierBrch = breaches.filter((b) => b.supplierId === supplierId && b.branchCode === branchCode);
    if (supplierBrch.length === 0) throw new Error(`No breaches found for supplier ${supplierId} at branch ${branchCode}`);

    const lines: AutoPOLine[] = supplierBrch.map((b) => ({
      lineId:      `APOL-${this.lineCounter++}`,
      sku:         b.sku,
      productName: b.productName,
      orderedQty:  b.suggestedQty,
      unitCost:    b.unitCost,
      lineTotal:   b.lineTotal,
      reorderPoint: b.reorderPoint,
      currentStock: b.currentStock,
    }));

    const totalQty   = lines.reduce((s, l) => s + l.orderedQty, 0);
    const totalValue = Math.round(lines.reduce((s, l) => s + l.lineTotal, 0) * 100) / 100;
    const maxLead    = Math.max(...supplierBrch.map((b) => b.leadTimeDays));
    const expectedDelivery = new Date(new Date(now).getTime() + maxLead * 86400000).toISOString().slice(0, 10);
    const poNo       = `APO-${branchCode}-${now.slice(0, 10).replace(/-/g, "")}-${String(this.counter++).padStart(4, "0")}`;

    return {
      poId:          `APOID-${Date.now()}-${this.counter}`,
      poNo,
      supplierId,
      supplierName:  supplierBrch[0].supplierName,
      branchCode,
      status:        "DRAFT",
      lines,
      totalLines:    lines.length,
      totalQty,
      totalValue,
      isAutoGenerated: true,
      generatedAt:   now,
      expectedDelivery,
    };
  }

  /**
   * Consolidate all breaches into POs grouped by supplier × branch.
   * Returns one PO per unique supplierId+branchCode combination.
   */
  public static consolidatePOs(breaches: ReorderBreach[]): AutoPurchaseOrder[] {
    const groups = new Map<string, ReorderBreach[]>();
    for (const b of breaches) {
      const key = `${b.supplierId}__${b.branchCode}`;
      const arr  = groups.get(key) ?? [];
      arr.push(b);
      groups.set(key, arr);
    }
    return Array.from(groups.entries()).map(([key, grpBreaches]) => {
      const [supplierId, branchCode] = key.split("__");
      return this.generatePO(grpBreaches, supplierId, branchCode);
    });
  }

  /** Submit PO to supplier */
  public static submit(po: AutoPurchaseOrder, submittedBy: string): AutoPurchaseOrder {
    if (po.status !== "DRAFT") throw new Error(`Cannot submit — status is ${po.status}`);
    return { ...po, status: "SUBMITTED", submittedAt: new Date().toISOString() };
  }

  /** Mark supplier acknowledgement */
  public static acknowledge(po: AutoPurchaseOrder): AutoPurchaseOrder {
    if (po.status !== "SUBMITTED") throw new Error(`Cannot acknowledge — status is ${po.status}`);
    return { ...po, status: "ACKNOWLEDGED", acknowledgedAt: new Date().toISOString() };
  }

  /** Cancel PO */
  public static cancel(po: AutoPurchaseOrder, reason: string): AutoPurchaseOrder {
    if (po.status === "ACKNOWLEDGED") throw new Error("Cannot cancel — already ACKNOWLEDGED");
    return { ...po, status: "CANCELLED", cancelledAt: new Date().toISOString(), cancelReason: reason };
  }

  /** Summary across a set of auto-POs */
  public static poSummary(pos: AutoPurchaseOrder[]): {
    totalPOs:     number;
    totalValue:   number;
    totalQty:     number;
    byStatus:     Record<AutoPOStatus, number>;
    criticalLines: number;
  } {
    const byStatus = {} as Record<AutoPOStatus, number>;
    let totalValue = 0, totalQty = 0, criticalLines = 0;
    for (const po of pos) {
      byStatus[po.status] = (byStatus[po.status] || 0) + 1;
      totalValue += po.totalValue;
      totalQty   += po.totalQty;
    }
    return {
      totalPOs:  pos.length,
      totalValue: Math.round(totalValue * 100) / 100,
      totalQty,
      byStatus,
      criticalLines,
    };
  }
}

export default AutoPOEngine;
